// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: application.proto

package com.ua.mytrinity.tv_client.proto;

public final class Application {
  private Application() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ApplicationInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.ApplicationInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .proto.ApplicationInfo.ApplicationType type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>required .proto.ApplicationInfo.ApplicationType type = 1;</code>
     */
    com.ua.mytrinity.tv_client.proto.Application.ApplicationInfo.ApplicationType getType();
  }
  /**
   * Protobuf type {@code proto.ApplicationInfo}
   */
  public  static final class ApplicationInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.ApplicationInfo)
      ApplicationInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ApplicationInfo.newBuilder() to construct.
    private ApplicationInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ApplicationInfo() {
      type_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ApplicationInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              com.ua.mytrinity.tv_client.proto.Application.ApplicationInfo.ApplicationType value = com.ua.mytrinity.tv_client.proto.Application.ApplicationInfo.ApplicationType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = rawValue;
              }
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ua.mytrinity.tv_client.proto.Application.internal_static_proto_ApplicationInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ua.mytrinity.tv_client.proto.Application.internal_static_proto_ApplicationInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ua.mytrinity.tv_client.proto.Application.ApplicationInfo.class, com.ua.mytrinity.tv_client.proto.Application.ApplicationInfo.Builder.class);
    }

    /**
     * Protobuf enum {@code proto.ApplicationInfo.ApplicationType}
     */
    public enum ApplicationType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>AT_Unknown = 0;</code>
       */
      AT_Unknown(0),
      /**
       * <code>AT_TRINITY_Player = 1;</code>
       */
      AT_TRINITY_Player(1),
      /**
       * <code>AT_SWEET_TV_Player = 2;</code>
       */
      AT_SWEET_TV_Player(2),
      /**
       * <code>AT_CACTUS_Player = 3;</code>
       */
      AT_CACTUS_Player(3),
      /**
       * <code>AT_Alpha_IP = 4;</code>
       */
      AT_Alpha_IP(4),
      /**
       * <code>AT_GRIZLI_Player = 5;</code>
       */
      AT_GRIZLI_Player(5),
      /**
       * <code>AT_Bravis_TV_Player = 6;</code>
       */
      AT_Bravis_TV_Player(6),
      /**
       * <code>AT_Startelecom_TV = 7;</code>
       */
      AT_Startelecom_TV(7),
      /**
       * <code>AT_Apelsin = 8;</code>
       */
      AT_Apelsin(8),
      /**
       * <code>AT_IMPERIAL_TV = 9;</code>
       */
      AT_IMPERIAL_TV(9),
      /**
       * <code>AT_AIWA = 10;</code>
       */
      AT_AIWA(10),
      /**
       * <code>AT_Kahovka = 11;</code>
       */
      AT_Kahovka(11),
      ;

      /**
       * <code>AT_Unknown = 0;</code>
       */
      public static final int AT_Unknown_VALUE = 0;
      /**
       * <code>AT_TRINITY_Player = 1;</code>
       */
      public static final int AT_TRINITY_Player_VALUE = 1;
      /**
       * <code>AT_SWEET_TV_Player = 2;</code>
       */
      public static final int AT_SWEET_TV_Player_VALUE = 2;
      /**
       * <code>AT_CACTUS_Player = 3;</code>
       */
      public static final int AT_CACTUS_Player_VALUE = 3;
      /**
       * <code>AT_Alpha_IP = 4;</code>
       */
      public static final int AT_Alpha_IP_VALUE = 4;
      /**
       * <code>AT_GRIZLI_Player = 5;</code>
       */
      public static final int AT_GRIZLI_Player_VALUE = 5;
      /**
       * <code>AT_Bravis_TV_Player = 6;</code>
       */
      public static final int AT_Bravis_TV_Player_VALUE = 6;
      /**
       * <code>AT_Startelecom_TV = 7;</code>
       */
      public static final int AT_Startelecom_TV_VALUE = 7;
      /**
       * <code>AT_Apelsin = 8;</code>
       */
      public static final int AT_Apelsin_VALUE = 8;
      /**
       * <code>AT_IMPERIAL_TV = 9;</code>
       */
      public static final int AT_IMPERIAL_TV_VALUE = 9;
      /**
       * <code>AT_AIWA = 10;</code>
       */
      public static final int AT_AIWA_VALUE = 10;
      /**
       * <code>AT_Kahovka = 11;</code>
       */
      public static final int AT_Kahovka_VALUE = 11;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static ApplicationType valueOf(int value) {
        return forNumber(value);
      }

      public static ApplicationType forNumber(int value) {
        switch (value) {
          case 0: return AT_Unknown;
          case 1: return AT_TRINITY_Player;
          case 2: return AT_SWEET_TV_Player;
          case 3: return AT_CACTUS_Player;
          case 4: return AT_Alpha_IP;
          case 5: return AT_GRIZLI_Player;
          case 6: return AT_Bravis_TV_Player;
          case 7: return AT_Startelecom_TV;
          case 8: return AT_Apelsin;
          case 9: return AT_IMPERIAL_TV;
          case 10: return AT_AIWA;
          case 11: return AT_Kahovka;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<ApplicationType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          ApplicationType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ApplicationType>() {
              public ApplicationType findValueByNumber(int number) {
                return ApplicationType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.ua.mytrinity.tv_client.proto.Application.ApplicationInfo.getDescriptor().getEnumTypes().get(0);
      }

      private static final ApplicationType[] VALUES = values();

      public static ApplicationType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private ApplicationType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:proto.ApplicationInfo.ApplicationType)
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>required .proto.ApplicationInfo.ApplicationType type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required .proto.ApplicationInfo.ApplicationType type = 1;</code>
     */
    public com.ua.mytrinity.tv_client.proto.Application.ApplicationInfo.ApplicationType getType() {
      @SuppressWarnings("deprecation")
      com.ua.mytrinity.tv_client.proto.Application.ApplicationInfo.ApplicationType result = com.ua.mytrinity.tv_client.proto.Application.ApplicationInfo.ApplicationType.valueOf(type_);
      return result == null ? com.ua.mytrinity.tv_client.proto.Application.ApplicationInfo.ApplicationType.AT_Unknown : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeEnum(1, type_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ua.mytrinity.tv_client.proto.Application.ApplicationInfo)) {
        return super.equals(obj);
      }
      com.ua.mytrinity.tv_client.proto.Application.ApplicationInfo other = (com.ua.mytrinity.tv_client.proto.Application.ApplicationInfo) obj;

      if (hasType() != other.hasType()) return false;
      if (hasType()) {
        if (type_ != other.type_) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasType()) {
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + type_;
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ua.mytrinity.tv_client.proto.Application.ApplicationInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ua.mytrinity.tv_client.proto.Application.ApplicationInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ua.mytrinity.tv_client.proto.Application.ApplicationInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ua.mytrinity.tv_client.proto.Application.ApplicationInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ua.mytrinity.tv_client.proto.Application.ApplicationInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ua.mytrinity.tv_client.proto.Application.ApplicationInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ua.mytrinity.tv_client.proto.Application.ApplicationInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ua.mytrinity.tv_client.proto.Application.ApplicationInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ua.mytrinity.tv_client.proto.Application.ApplicationInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ua.mytrinity.tv_client.proto.Application.ApplicationInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ua.mytrinity.tv_client.proto.Application.ApplicationInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ua.mytrinity.tv_client.proto.Application.ApplicationInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ua.mytrinity.tv_client.proto.Application.ApplicationInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.ApplicationInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.ApplicationInfo)
        com.ua.mytrinity.tv_client.proto.Application.ApplicationInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ua.mytrinity.tv_client.proto.Application.internal_static_proto_ApplicationInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ua.mytrinity.tv_client.proto.Application.internal_static_proto_ApplicationInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ua.mytrinity.tv_client.proto.Application.ApplicationInfo.class, com.ua.mytrinity.tv_client.proto.Application.ApplicationInfo.Builder.class);
      }

      // Construct using com.ua.mytrinity.tv_client.proto.Application.ApplicationInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ua.mytrinity.tv_client.proto.Application.internal_static_proto_ApplicationInfo_descriptor;
      }

      @java.lang.Override
      public com.ua.mytrinity.tv_client.proto.Application.ApplicationInfo getDefaultInstanceForType() {
        return com.ua.mytrinity.tv_client.proto.Application.ApplicationInfo.getDefaultInstance();
      }

      @java.lang.Override
      public com.ua.mytrinity.tv_client.proto.Application.ApplicationInfo build() {
        com.ua.mytrinity.tv_client.proto.Application.ApplicationInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.ua.mytrinity.tv_client.proto.Application.ApplicationInfo buildPartial() {
        com.ua.mytrinity.tv_client.proto.Application.ApplicationInfo result = new com.ua.mytrinity.tv_client.proto.Application.ApplicationInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ua.mytrinity.tv_client.proto.Application.ApplicationInfo) {
          return mergeFrom((com.ua.mytrinity.tv_client.proto.Application.ApplicationInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ua.mytrinity.tv_client.proto.Application.ApplicationInfo other) {
        if (other == com.ua.mytrinity.tv_client.proto.Application.ApplicationInfo.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasType()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ua.mytrinity.tv_client.proto.Application.ApplicationInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ua.mytrinity.tv_client.proto.Application.ApplicationInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int type_ = 0;
      /**
       * <code>required .proto.ApplicationInfo.ApplicationType type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required .proto.ApplicationInfo.ApplicationType type = 1;</code>
       */
      public com.ua.mytrinity.tv_client.proto.Application.ApplicationInfo.ApplicationType getType() {
        @SuppressWarnings("deprecation")
        com.ua.mytrinity.tv_client.proto.Application.ApplicationInfo.ApplicationType result = com.ua.mytrinity.tv_client.proto.Application.ApplicationInfo.ApplicationType.valueOf(type_);
        return result == null ? com.ua.mytrinity.tv_client.proto.Application.ApplicationInfo.ApplicationType.AT_Unknown : result;
      }
      /**
       * <code>required .proto.ApplicationInfo.ApplicationType type = 1;</code>
       */
      public Builder setType(com.ua.mytrinity.tv_client.proto.Application.ApplicationInfo.ApplicationType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .proto.ApplicationInfo.ApplicationType type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.ApplicationInfo)
    }

    // @@protoc_insertion_point(class_scope:proto.ApplicationInfo)
    private static final com.ua.mytrinity.tv_client.proto.Application.ApplicationInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ua.mytrinity.tv_client.proto.Application.ApplicationInfo();
    }

    public static com.ua.mytrinity.tv_client.proto.Application.ApplicationInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<ApplicationInfo>
        PARSER = new com.google.protobuf.AbstractParser<ApplicationInfo>() {
      @java.lang.Override
      public ApplicationInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ApplicationInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ApplicationInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ApplicationInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.ua.mytrinity.tv_client.proto.Application.ApplicationInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_ApplicationInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_ApplicationInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021application.proto\022\005proto\"\310\002\n\017Applicati" +
      "onInfo\0224\n\004type\030\001 \002(\0162&.proto.Application" +
      "Info.ApplicationType\"\376\001\n\017ApplicationType" +
      "\022\016\n\nAT_Unknown\020\000\022\025\n\021AT_TRINITY_Player\020\001\022" +
      "\026\n\022AT_SWEET_TV_Player\020\002\022\024\n\020AT_CACTUS_Pla" +
      "yer\020\003\022\017\n\013AT_Alpha_IP\020\004\022\024\n\020AT_GRIZLI_Play" +
      "er\020\005\022\027\n\023AT_Bravis_TV_Player\020\006\022\025\n\021AT_Star" +
      "telecom_TV\020\007\022\016\n\nAT_Apelsin\020\010\022\022\n\016AT_IMPER" +
      "IAL_TV\020\t\022\013\n\007AT_AIWA\020\n\022\016\n\nAT_Kahovka\020\013B\"\n" +
      " com.ua.mytrinity.tv_client.proto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_proto_ApplicationInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_ApplicationInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_ApplicationInfo_descriptor,
        new java.lang.String[] { "Type", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
