// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: channel_rating.proto

package com.ua.mytrinity.tv_client.proto;

public final class ChannelRatingOuterClass {
  private ChannelRatingOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ChannelRatingOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.ChannelRating)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 channel_id = 1;</code>
     */
    boolean hasChannelId();
    /**
     * <code>required int32 channel_id = 1;</code>
     */
    int getChannelId();

    /**
     * <code>required float rating = 2;</code>
     */
    boolean hasRating();
    /**
     * <code>required float rating = 2;</code>
     */
    float getRating();
  }
  /**
   * Protobuf type {@code proto.ChannelRating}
   */
  public  static final class ChannelRating extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.ChannelRating)
      ChannelRatingOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ChannelRating.newBuilder() to construct.
    private ChannelRating(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ChannelRating() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ChannelRating(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              channelId_ = input.readInt32();
              break;
            }
            case 21: {
              bitField0_ |= 0x00000002;
              rating_ = input.readFloat();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.internal_static_proto_ChannelRating_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.internal_static_proto_ChannelRating_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.ChannelRating.class, com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.ChannelRating.Builder.class);
    }

    private int bitField0_;
    public static final int CHANNEL_ID_FIELD_NUMBER = 1;
    private int channelId_;
    /**
     * <code>required int32 channel_id = 1;</code>
     */
    public boolean hasChannelId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required int32 channel_id = 1;</code>
     */
    public int getChannelId() {
      return channelId_;
    }

    public static final int RATING_FIELD_NUMBER = 2;
    private float rating_;
    /**
     * <code>required float rating = 2;</code>
     */
    public boolean hasRating() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required float rating = 2;</code>
     */
    public float getRating() {
      return rating_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasChannelId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRating()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(1, channelId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeFloat(2, rating_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, channelId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, rating_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.ChannelRating)) {
        return super.equals(obj);
      }
      com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.ChannelRating other = (com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.ChannelRating) obj;

      if (hasChannelId() != other.hasChannelId()) return false;
      if (hasChannelId()) {
        if (getChannelId()
            != other.getChannelId()) return false;
      }
      if (hasRating() != other.hasRating()) return false;
      if (hasRating()) {
        if (java.lang.Float.floatToIntBits(getRating())
            != java.lang.Float.floatToIntBits(
                other.getRating())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasChannelId()) {
        hash = (37 * hash) + CHANNEL_ID_FIELD_NUMBER;
        hash = (53 * hash) + getChannelId();
      }
      if (hasRating()) {
        hash = (37 * hash) + RATING_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getRating());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.ChannelRating parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.ChannelRating parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.ChannelRating parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.ChannelRating parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.ChannelRating parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.ChannelRating parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.ChannelRating parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.ChannelRating parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.ChannelRating parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.ChannelRating parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.ChannelRating parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.ChannelRating parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.ChannelRating prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.ChannelRating}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.ChannelRating)
        com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.ChannelRatingOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.internal_static_proto_ChannelRating_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.internal_static_proto_ChannelRating_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.ChannelRating.class, com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.ChannelRating.Builder.class);
      }

      // Construct using com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.ChannelRating.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        channelId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        rating_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.internal_static_proto_ChannelRating_descriptor;
      }

      @java.lang.Override
      public com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.ChannelRating getDefaultInstanceForType() {
        return com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.ChannelRating.getDefaultInstance();
      }

      @java.lang.Override
      public com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.ChannelRating build() {
        com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.ChannelRating result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.ChannelRating buildPartial() {
        com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.ChannelRating result = new com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.ChannelRating(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.channelId_ = channelId_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.rating_ = rating_;
          to_bitField0_ |= 0x00000002;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.ChannelRating) {
          return mergeFrom((com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.ChannelRating)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.ChannelRating other) {
        if (other == com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.ChannelRating.getDefaultInstance()) return this;
        if (other.hasChannelId()) {
          setChannelId(other.getChannelId());
        }
        if (other.hasRating()) {
          setRating(other.getRating());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasChannelId()) {
          return false;
        }
        if (!hasRating()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.ChannelRating parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.ChannelRating) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int channelId_ ;
      /**
       * <code>required int32 channel_id = 1;</code>
       */
      public boolean hasChannelId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required int32 channel_id = 1;</code>
       */
      public int getChannelId() {
        return channelId_;
      }
      /**
       * <code>required int32 channel_id = 1;</code>
       */
      public Builder setChannelId(int value) {
        bitField0_ |= 0x00000001;
        channelId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 channel_id = 1;</code>
       */
      public Builder clearChannelId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        channelId_ = 0;
        onChanged();
        return this;
      }

      private float rating_ ;
      /**
       * <code>required float rating = 2;</code>
       */
      public boolean hasRating() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required float rating = 2;</code>
       */
      public float getRating() {
        return rating_;
      }
      /**
       * <code>required float rating = 2;</code>
       */
      public Builder setRating(float value) {
        bitField0_ |= 0x00000002;
        rating_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float rating = 2;</code>
       */
      public Builder clearRating() {
        bitField0_ = (bitField0_ & ~0x00000002);
        rating_ = 0F;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.ChannelRating)
    }

    // @@protoc_insertion_point(class_scope:proto.ChannelRating)
    private static final com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.ChannelRating DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.ChannelRating();
    }

    public static com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.ChannelRating getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<ChannelRating>
        PARSER = new com.google.protobuf.AbstractParser<ChannelRating>() {
      @java.lang.Override
      public ChannelRating parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ChannelRating(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ChannelRating> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ChannelRating> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.ChannelRating getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GetChannelsRatingRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.GetChannelsRatingRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string auth = 1;</code>
     */
    boolean hasAuth();
    /**
     * <code>required string auth = 1;</code>
     */
    java.lang.String getAuth();
    /**
     * <code>required string auth = 1;</code>
     */
    com.google.protobuf.ByteString
        getAuthBytes();

    /**
     * <code>repeated int32 channels = 2;</code>
     */
    java.util.List<java.lang.Integer> getChannelsList();
    /**
     * <code>repeated int32 channels = 2;</code>
     */
    int getChannelsCount();
    /**
     * <code>repeated int32 channels = 2;</code>
     */
    int getChannels(int index);

    /**
     * <code>optional uint32 limit_count = 3;</code>
     */
    boolean hasLimitCount();
    /**
     * <code>optional uint32 limit_count = 3;</code>
     */
    int getLimitCount();

    /**
     * <code>optional int32 company_id = 4;</code>
     */
    boolean hasCompanyId();
    /**
     * <code>optional int32 company_id = 4;</code>
     */
    int getCompanyId();
  }
  /**
   * Protobuf type {@code proto.GetChannelsRatingRequest}
   */
  public  static final class GetChannelsRatingRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.GetChannelsRatingRequest)
      GetChannelsRatingRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GetChannelsRatingRequest.newBuilder() to construct.
    private GetChannelsRatingRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetChannelsRatingRequest() {
      auth_ = "";
      channels_ = emptyIntList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GetChannelsRatingRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              auth_ = bs;
              break;
            }
            case 16: {
              if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                channels_ = newIntList();
                mutable_bitField0_ |= 0x00000002;
              }
              channels_.addInt(input.readInt32());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000002) != 0) && input.getBytesUntilLimit() > 0) {
                channels_ = newIntList();
                mutable_bitField0_ |= 0x00000002;
              }
              while (input.getBytesUntilLimit() > 0) {
                channels_.addInt(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 24: {
              bitField0_ |= 0x00000002;
              limitCount_ = input.readUInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000004;
              companyId_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) != 0)) {
          channels_.makeImmutable(); // C
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.internal_static_proto_GetChannelsRatingRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.internal_static_proto_GetChannelsRatingRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.GetChannelsRatingRequest.class, com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.GetChannelsRatingRequest.Builder.class);
    }

    private int bitField0_;
    public static final int AUTH_FIELD_NUMBER = 1;
    private volatile java.lang.Object auth_;
    /**
     * <code>required string auth = 1;</code>
     */
    public boolean hasAuth() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required string auth = 1;</code>
     */
    public java.lang.String getAuth() {
      java.lang.Object ref = auth_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          auth_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string auth = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAuthBytes() {
      java.lang.Object ref = auth_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        auth_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CHANNELS_FIELD_NUMBER = 2;
    private com.google.protobuf.Internal.IntList channels_;
    /**
     * <code>repeated int32 channels = 2;</code>
     */
    public java.util.List<java.lang.Integer>
        getChannelsList() {
      return channels_;
    }
    /**
     * <code>repeated int32 channels = 2;</code>
     */
    public int getChannelsCount() {
      return channels_.size();
    }
    /**
     * <code>repeated int32 channels = 2;</code>
     */
    public int getChannels(int index) {
      return channels_.getInt(index);
    }

    public static final int LIMIT_COUNT_FIELD_NUMBER = 3;
    private int limitCount_;
    /**
     * <code>optional uint32 limit_count = 3;</code>
     */
    public boolean hasLimitCount() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional uint32 limit_count = 3;</code>
     */
    public int getLimitCount() {
      return limitCount_;
    }

    public static final int COMPANY_ID_FIELD_NUMBER = 4;
    private int companyId_;
    /**
     * <code>optional int32 company_id = 4;</code>
     */
    public boolean hasCompanyId() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional int32 company_id = 4;</code>
     */
    public int getCompanyId() {
      return companyId_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasAuth()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, auth_);
      }
      for (int i = 0; i < channels_.size(); i++) {
        output.writeInt32(2, channels_.getInt(i));
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeUInt32(3, limitCount_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeInt32(4, companyId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, auth_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < channels_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(channels_.getInt(i));
        }
        size += dataSize;
        size += 1 * getChannelsList().size();
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, limitCount_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, companyId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.GetChannelsRatingRequest)) {
        return super.equals(obj);
      }
      com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.GetChannelsRatingRequest other = (com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.GetChannelsRatingRequest) obj;

      if (hasAuth() != other.hasAuth()) return false;
      if (hasAuth()) {
        if (!getAuth()
            .equals(other.getAuth())) return false;
      }
      if (!getChannelsList()
          .equals(other.getChannelsList())) return false;
      if (hasLimitCount() != other.hasLimitCount()) return false;
      if (hasLimitCount()) {
        if (getLimitCount()
            != other.getLimitCount()) return false;
      }
      if (hasCompanyId() != other.hasCompanyId()) return false;
      if (hasCompanyId()) {
        if (getCompanyId()
            != other.getCompanyId()) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasAuth()) {
        hash = (37 * hash) + AUTH_FIELD_NUMBER;
        hash = (53 * hash) + getAuth().hashCode();
      }
      if (getChannelsCount() > 0) {
        hash = (37 * hash) + CHANNELS_FIELD_NUMBER;
        hash = (53 * hash) + getChannelsList().hashCode();
      }
      if (hasLimitCount()) {
        hash = (37 * hash) + LIMIT_COUNT_FIELD_NUMBER;
        hash = (53 * hash) + getLimitCount();
      }
      if (hasCompanyId()) {
        hash = (37 * hash) + COMPANY_ID_FIELD_NUMBER;
        hash = (53 * hash) + getCompanyId();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.GetChannelsRatingRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.GetChannelsRatingRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.GetChannelsRatingRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.GetChannelsRatingRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.GetChannelsRatingRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.GetChannelsRatingRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.GetChannelsRatingRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.GetChannelsRatingRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.GetChannelsRatingRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.GetChannelsRatingRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.GetChannelsRatingRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.GetChannelsRatingRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.GetChannelsRatingRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.GetChannelsRatingRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.GetChannelsRatingRequest)
        com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.GetChannelsRatingRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.internal_static_proto_GetChannelsRatingRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.internal_static_proto_GetChannelsRatingRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.GetChannelsRatingRequest.class, com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.GetChannelsRatingRequest.Builder.class);
      }

      // Construct using com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.GetChannelsRatingRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        auth_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        channels_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000002);
        limitCount_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        companyId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.internal_static_proto_GetChannelsRatingRequest_descriptor;
      }

      @java.lang.Override
      public com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.GetChannelsRatingRequest getDefaultInstanceForType() {
        return com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.GetChannelsRatingRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.GetChannelsRatingRequest build() {
        com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.GetChannelsRatingRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.GetChannelsRatingRequest buildPartial() {
        com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.GetChannelsRatingRequest result = new com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.GetChannelsRatingRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.auth_ = auth_;
        if (((bitField0_ & 0x00000002) != 0)) {
          channels_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.channels_ = channels_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.limitCount_ = limitCount_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.companyId_ = companyId_;
          to_bitField0_ |= 0x00000004;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.GetChannelsRatingRequest) {
          return mergeFrom((com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.GetChannelsRatingRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.GetChannelsRatingRequest other) {
        if (other == com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.GetChannelsRatingRequest.getDefaultInstance()) return this;
        if (other.hasAuth()) {
          bitField0_ |= 0x00000001;
          auth_ = other.auth_;
          onChanged();
        }
        if (!other.channels_.isEmpty()) {
          if (channels_.isEmpty()) {
            channels_ = other.channels_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureChannelsIsMutable();
            channels_.addAll(other.channels_);
          }
          onChanged();
        }
        if (other.hasLimitCount()) {
          setLimitCount(other.getLimitCount());
        }
        if (other.hasCompanyId()) {
          setCompanyId(other.getCompanyId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasAuth()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.GetChannelsRatingRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.GetChannelsRatingRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object auth_ = "";
      /**
       * <code>required string auth = 1;</code>
       */
      public boolean hasAuth() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required string auth = 1;</code>
       */
      public java.lang.String getAuth() {
        java.lang.Object ref = auth_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            auth_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string auth = 1;</code>
       */
      public com.google.protobuf.ByteString
          getAuthBytes() {
        java.lang.Object ref = auth_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          auth_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string auth = 1;</code>
       */
      public Builder setAuth(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        auth_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string auth = 1;</code>
       */
      public Builder clearAuth() {
        bitField0_ = (bitField0_ & ~0x00000001);
        auth_ = getDefaultInstance().getAuth();
        onChanged();
        return this;
      }
      /**
       * <code>required string auth = 1;</code>
       */
      public Builder setAuthBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        auth_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.IntList channels_ = emptyIntList();
      private void ensureChannelsIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          channels_ = mutableCopy(channels_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated int32 channels = 2;</code>
       */
      public java.util.List<java.lang.Integer>
          getChannelsList() {
        return ((bitField0_ & 0x00000002) != 0) ?
                 java.util.Collections.unmodifiableList(channels_) : channels_;
      }
      /**
       * <code>repeated int32 channels = 2;</code>
       */
      public int getChannelsCount() {
        return channels_.size();
      }
      /**
       * <code>repeated int32 channels = 2;</code>
       */
      public int getChannels(int index) {
        return channels_.getInt(index);
      }
      /**
       * <code>repeated int32 channels = 2;</code>
       */
      public Builder setChannels(
          int index, int value) {
        ensureChannelsIsMutable();
        channels_.setInt(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 channels = 2;</code>
       */
      public Builder addChannels(int value) {
        ensureChannelsIsMutable();
        channels_.addInt(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 channels = 2;</code>
       */
      public Builder addAllChannels(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureChannelsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, channels_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 channels = 2;</code>
       */
      public Builder clearChannels() {
        channels_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }

      private int limitCount_ ;
      /**
       * <code>optional uint32 limit_count = 3;</code>
       */
      public boolean hasLimitCount() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional uint32 limit_count = 3;</code>
       */
      public int getLimitCount() {
        return limitCount_;
      }
      /**
       * <code>optional uint32 limit_count = 3;</code>
       */
      public Builder setLimitCount(int value) {
        bitField0_ |= 0x00000004;
        limitCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 limit_count = 3;</code>
       */
      public Builder clearLimitCount() {
        bitField0_ = (bitField0_ & ~0x00000004);
        limitCount_ = 0;
        onChanged();
        return this;
      }

      private int companyId_ ;
      /**
       * <code>optional int32 company_id = 4;</code>
       */
      public boolean hasCompanyId() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional int32 company_id = 4;</code>
       */
      public int getCompanyId() {
        return companyId_;
      }
      /**
       * <code>optional int32 company_id = 4;</code>
       */
      public Builder setCompanyId(int value) {
        bitField0_ |= 0x00000008;
        companyId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 company_id = 4;</code>
       */
      public Builder clearCompanyId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        companyId_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.GetChannelsRatingRequest)
    }

    // @@protoc_insertion_point(class_scope:proto.GetChannelsRatingRequest)
    private static final com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.GetChannelsRatingRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.GetChannelsRatingRequest();
    }

    public static com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.GetChannelsRatingRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<GetChannelsRatingRequest>
        PARSER = new com.google.protobuf.AbstractParser<GetChannelsRatingRequest>() {
      @java.lang.Override
      public GetChannelsRatingRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GetChannelsRatingRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GetChannelsRatingRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetChannelsRatingRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.GetChannelsRatingRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GetChannelsRatingResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.GetChannelsRatingResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .proto.GetChannelsRatingResponse.Result status = 1;</code>
     */
    boolean hasStatus();
    /**
     * <code>required .proto.GetChannelsRatingResponse.Result status = 1;</code>
     */
    com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.GetChannelsRatingResponse.Result getStatus();

    /**
     * <code>repeated .proto.ChannelRating list = 2;</code>
     */
    java.util.List<com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.ChannelRating> 
        getListList();
    /**
     * <code>repeated .proto.ChannelRating list = 2;</code>
     */
    com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.ChannelRating getList(int index);
    /**
     * <code>repeated .proto.ChannelRating list = 2;</code>
     */
    int getListCount();
    /**
     * <code>repeated .proto.ChannelRating list = 2;</code>
     */
    java.util.List<? extends com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.ChannelRatingOrBuilder> 
        getListOrBuilderList();
    /**
     * <code>repeated .proto.ChannelRating list = 2;</code>
     */
    com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.ChannelRatingOrBuilder getListOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code proto.GetChannelsRatingResponse}
   */
  public  static final class GetChannelsRatingResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.GetChannelsRatingResponse)
      GetChannelsRatingResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GetChannelsRatingResponse.newBuilder() to construct.
    private GetChannelsRatingResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetChannelsRatingResponse() {
      status_ = 0;
      list_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GetChannelsRatingResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.GetChannelsRatingResponse.Result value = com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.GetChannelsRatingResponse.Result.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                status_ = rawValue;
              }
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                list_ = new java.util.ArrayList<com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.ChannelRating>();
                mutable_bitField0_ |= 0x00000002;
              }
              list_.add(
                  input.readMessage(com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.ChannelRating.PARSER, extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) != 0)) {
          list_ = java.util.Collections.unmodifiableList(list_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.internal_static_proto_GetChannelsRatingResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.internal_static_proto_GetChannelsRatingResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.GetChannelsRatingResponse.class, com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.GetChannelsRatingResponse.Builder.class);
    }

    /**
     * Protobuf enum {@code proto.GetChannelsRatingResponse.Result}
     */
    public enum Result
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>OK = 0;</code>
       */
      OK(0),
      /**
       * <code>NoAuth = 1;</code>
       */
      NoAuth(1),
      ;

      /**
       * <code>OK = 0;</code>
       */
      public static final int OK_VALUE = 0;
      /**
       * <code>NoAuth = 1;</code>
       */
      public static final int NoAuth_VALUE = 1;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Result valueOf(int value) {
        return forNumber(value);
      }

      public static Result forNumber(int value) {
        switch (value) {
          case 0: return OK;
          case 1: return NoAuth;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Result>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Result> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Result>() {
              public Result findValueByNumber(int number) {
                return Result.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.GetChannelsRatingResponse.getDescriptor().getEnumTypes().get(0);
      }

      private static final Result[] VALUES = values();

      public static Result valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Result(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:proto.GetChannelsRatingResponse.Result)
    }

    private int bitField0_;
    public static final int STATUS_FIELD_NUMBER = 1;
    private int status_;
    /**
     * <code>required .proto.GetChannelsRatingResponse.Result status = 1;</code>
     */
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required .proto.GetChannelsRatingResponse.Result status = 1;</code>
     */
    public com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.GetChannelsRatingResponse.Result getStatus() {
      @SuppressWarnings("deprecation")
      com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.GetChannelsRatingResponse.Result result = com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.GetChannelsRatingResponse.Result.valueOf(status_);
      return result == null ? com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.GetChannelsRatingResponse.Result.OK : result;
    }

    public static final int LIST_FIELD_NUMBER = 2;
    private java.util.List<com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.ChannelRating> list_;
    /**
     * <code>repeated .proto.ChannelRating list = 2;</code>
     */
    public java.util.List<com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.ChannelRating> getListList() {
      return list_;
    }
    /**
     * <code>repeated .proto.ChannelRating list = 2;</code>
     */
    public java.util.List<? extends com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.ChannelRatingOrBuilder> 
        getListOrBuilderList() {
      return list_;
    }
    /**
     * <code>repeated .proto.ChannelRating list = 2;</code>
     */
    public int getListCount() {
      return list_.size();
    }
    /**
     * <code>repeated .proto.ChannelRating list = 2;</code>
     */
    public com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.ChannelRating getList(int index) {
      return list_.get(index);
    }
    /**
     * <code>repeated .proto.ChannelRating list = 2;</code>
     */
    public com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.ChannelRatingOrBuilder getListOrBuilder(
        int index) {
      return list_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasStatus()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getListCount(); i++) {
        if (!getList(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeEnum(1, status_);
      }
      for (int i = 0; i < list_.size(); i++) {
        output.writeMessage(2, list_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, status_);
      }
      for (int i = 0; i < list_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, list_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.GetChannelsRatingResponse)) {
        return super.equals(obj);
      }
      com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.GetChannelsRatingResponse other = (com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.GetChannelsRatingResponse) obj;

      if (hasStatus() != other.hasStatus()) return false;
      if (hasStatus()) {
        if (status_ != other.status_) return false;
      }
      if (!getListList()
          .equals(other.getListList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasStatus()) {
        hash = (37 * hash) + STATUS_FIELD_NUMBER;
        hash = (53 * hash) + status_;
      }
      if (getListCount() > 0) {
        hash = (37 * hash) + LIST_FIELD_NUMBER;
        hash = (53 * hash) + getListList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.GetChannelsRatingResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.GetChannelsRatingResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.GetChannelsRatingResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.GetChannelsRatingResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.GetChannelsRatingResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.GetChannelsRatingResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.GetChannelsRatingResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.GetChannelsRatingResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.GetChannelsRatingResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.GetChannelsRatingResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.GetChannelsRatingResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.GetChannelsRatingResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.GetChannelsRatingResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.GetChannelsRatingResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.GetChannelsRatingResponse)
        com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.GetChannelsRatingResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.internal_static_proto_GetChannelsRatingResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.internal_static_proto_GetChannelsRatingResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.GetChannelsRatingResponse.class, com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.GetChannelsRatingResponse.Builder.class);
      }

      // Construct using com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.GetChannelsRatingResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getListFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        status_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (listBuilder_ == null) {
          list_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          listBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.internal_static_proto_GetChannelsRatingResponse_descriptor;
      }

      @java.lang.Override
      public com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.GetChannelsRatingResponse getDefaultInstanceForType() {
        return com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.GetChannelsRatingResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.GetChannelsRatingResponse build() {
        com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.GetChannelsRatingResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.GetChannelsRatingResponse buildPartial() {
        com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.GetChannelsRatingResponse result = new com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.GetChannelsRatingResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.status_ = status_;
        if (listBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0)) {
            list_ = java.util.Collections.unmodifiableList(list_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.list_ = list_;
        } else {
          result.list_ = listBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.GetChannelsRatingResponse) {
          return mergeFrom((com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.GetChannelsRatingResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.GetChannelsRatingResponse other) {
        if (other == com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.GetChannelsRatingResponse.getDefaultInstance()) return this;
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        if (listBuilder_ == null) {
          if (!other.list_.isEmpty()) {
            if (list_.isEmpty()) {
              list_ = other.list_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureListIsMutable();
              list_.addAll(other.list_);
            }
            onChanged();
          }
        } else {
          if (!other.list_.isEmpty()) {
            if (listBuilder_.isEmpty()) {
              listBuilder_.dispose();
              listBuilder_ = null;
              list_ = other.list_;
              bitField0_ = (bitField0_ & ~0x00000002);
              listBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getListFieldBuilder() : null;
            } else {
              listBuilder_.addAllMessages(other.list_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasStatus()) {
          return false;
        }
        for (int i = 0; i < getListCount(); i++) {
          if (!getList(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.GetChannelsRatingResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.GetChannelsRatingResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int status_ = 0;
      /**
       * <code>required .proto.GetChannelsRatingResponse.Result status = 1;</code>
       */
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required .proto.GetChannelsRatingResponse.Result status = 1;</code>
       */
      public com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.GetChannelsRatingResponse.Result getStatus() {
        @SuppressWarnings("deprecation")
        com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.GetChannelsRatingResponse.Result result = com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.GetChannelsRatingResponse.Result.valueOf(status_);
        return result == null ? com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.GetChannelsRatingResponse.Result.OK : result;
      }
      /**
       * <code>required .proto.GetChannelsRatingResponse.Result status = 1;</code>
       */
      public Builder setStatus(com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.GetChannelsRatingResponse.Result value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        status_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .proto.GetChannelsRatingResponse.Result status = 1;</code>
       */
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000001);
        status_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.ChannelRating> list_ =
        java.util.Collections.emptyList();
      private void ensureListIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          list_ = new java.util.ArrayList<com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.ChannelRating>(list_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.ChannelRating, com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.ChannelRating.Builder, com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.ChannelRatingOrBuilder> listBuilder_;

      /**
       * <code>repeated .proto.ChannelRating list = 2;</code>
       */
      public java.util.List<com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.ChannelRating> getListList() {
        if (listBuilder_ == null) {
          return java.util.Collections.unmodifiableList(list_);
        } else {
          return listBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .proto.ChannelRating list = 2;</code>
       */
      public int getListCount() {
        if (listBuilder_ == null) {
          return list_.size();
        } else {
          return listBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .proto.ChannelRating list = 2;</code>
       */
      public com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.ChannelRating getList(int index) {
        if (listBuilder_ == null) {
          return list_.get(index);
        } else {
          return listBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .proto.ChannelRating list = 2;</code>
       */
      public Builder setList(
          int index, com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.ChannelRating value) {
        if (listBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureListIsMutable();
          list_.set(index, value);
          onChanged();
        } else {
          listBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.ChannelRating list = 2;</code>
       */
      public Builder setList(
          int index, com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.ChannelRating.Builder builderForValue) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          list_.set(index, builderForValue.build());
          onChanged();
        } else {
          listBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.ChannelRating list = 2;</code>
       */
      public Builder addList(com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.ChannelRating value) {
        if (listBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureListIsMutable();
          list_.add(value);
          onChanged();
        } else {
          listBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.ChannelRating list = 2;</code>
       */
      public Builder addList(
          int index, com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.ChannelRating value) {
        if (listBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureListIsMutable();
          list_.add(index, value);
          onChanged();
        } else {
          listBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.ChannelRating list = 2;</code>
       */
      public Builder addList(
          com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.ChannelRating.Builder builderForValue) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          list_.add(builderForValue.build());
          onChanged();
        } else {
          listBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.ChannelRating list = 2;</code>
       */
      public Builder addList(
          int index, com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.ChannelRating.Builder builderForValue) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          list_.add(index, builderForValue.build());
          onChanged();
        } else {
          listBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.ChannelRating list = 2;</code>
       */
      public Builder addAllList(
          java.lang.Iterable<? extends com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.ChannelRating> values) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, list_);
          onChanged();
        } else {
          listBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .proto.ChannelRating list = 2;</code>
       */
      public Builder clearList() {
        if (listBuilder_ == null) {
          list_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          listBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .proto.ChannelRating list = 2;</code>
       */
      public Builder removeList(int index) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          list_.remove(index);
          onChanged();
        } else {
          listBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .proto.ChannelRating list = 2;</code>
       */
      public com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.ChannelRating.Builder getListBuilder(
          int index) {
        return getListFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .proto.ChannelRating list = 2;</code>
       */
      public com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.ChannelRatingOrBuilder getListOrBuilder(
          int index) {
        if (listBuilder_ == null) {
          return list_.get(index);  } else {
          return listBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .proto.ChannelRating list = 2;</code>
       */
      public java.util.List<? extends com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.ChannelRatingOrBuilder> 
           getListOrBuilderList() {
        if (listBuilder_ != null) {
          return listBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(list_);
        }
      }
      /**
       * <code>repeated .proto.ChannelRating list = 2;</code>
       */
      public com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.ChannelRating.Builder addListBuilder() {
        return getListFieldBuilder().addBuilder(
            com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.ChannelRating.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.ChannelRating list = 2;</code>
       */
      public com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.ChannelRating.Builder addListBuilder(
          int index) {
        return getListFieldBuilder().addBuilder(
            index, com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.ChannelRating.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.ChannelRating list = 2;</code>
       */
      public java.util.List<com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.ChannelRating.Builder> 
           getListBuilderList() {
        return getListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.ChannelRating, com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.ChannelRating.Builder, com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.ChannelRatingOrBuilder> 
          getListFieldBuilder() {
        if (listBuilder_ == null) {
          listBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.ChannelRating, com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.ChannelRating.Builder, com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.ChannelRatingOrBuilder>(
                  list_,
                  ((bitField0_ & 0x00000002) != 0),
                  getParentForChildren(),
                  isClean());
          list_ = null;
        }
        return listBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.GetChannelsRatingResponse)
    }

    // @@protoc_insertion_point(class_scope:proto.GetChannelsRatingResponse)
    private static final com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.GetChannelsRatingResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.GetChannelsRatingResponse();
    }

    public static com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.GetChannelsRatingResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<GetChannelsRatingResponse>
        PARSER = new com.google.protobuf.AbstractParser<GetChannelsRatingResponse>() {
      @java.lang.Override
      public GetChannelsRatingResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GetChannelsRatingResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GetChannelsRatingResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetChannelsRatingResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.ua.mytrinity.tv_client.proto.ChannelRatingOuterClass.GetChannelsRatingResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_ChannelRating_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_ChannelRating_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_GetChannelsRatingRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_GetChannelsRatingRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_GetChannelsRatingResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_GetChannelsRatingResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024channel_rating.proto\022\005proto\"3\n\rChannel" +
      "Rating\022\022\n\nchannel_id\030\001 \002(\005\022\016\n\006rating\030\002 \002" +
      "(\002\"c\n\030GetChannelsRatingRequest\022\014\n\004auth\030\001" +
      " \002(\t\022\020\n\010channels\030\002 \003(\005\022\023\n\013limit_count\030\003 " +
      "\001(\r\022\022\n\ncompany_id\030\004 \001(\005\"\226\001\n\031GetChannelsR" +
      "atingResponse\0227\n\006status\030\001 \002(\0162\'.proto.Ge" +
      "tChannelsRatingResponse.Result\022\"\n\004list\030\002" +
      " \003(\0132\024.proto.ChannelRating\"\034\n\006Result\022\006\n\002" +
      "OK\020\000\022\n\n\006NoAuth\020\001B\"\n com.ua.mytrinity.tv_" +
      "client.proto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_proto_ChannelRating_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_ChannelRating_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_ChannelRating_descriptor,
        new java.lang.String[] { "ChannelId", "Rating", });
    internal_static_proto_GetChannelsRatingRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_GetChannelsRatingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_GetChannelsRatingRequest_descriptor,
        new java.lang.String[] { "Auth", "Channels", "LimitCount", "CompanyId", });
    internal_static_proto_GetChannelsRatingResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_proto_GetChannelsRatingResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_GetChannelsRatingResponse_descriptor,
        new java.lang.String[] { "Status", "List", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
