// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: drm_link.proto

package com.ua.mytrinity.tv_client.proto;

public final class DrmLink {
  private DrmLink() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code proto.AllowedTracks}
   */
  public enum AllowedTracks
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>SD_ONLY = 0;</code>
     */
    SD_ONLY(0),
    /**
     * <code>SD_HD = 1;</code>
     */
    SD_HD(1),
    /**
     * <code>SD_UHD1 = 2;</code>
     */
    SD_UHD1(2),
    /**
     * <code>SD_UHD2 = 3;</code>
     */
    SD_UHD2(3),
    ;

    /**
     * <code>SD_ONLY = 0;</code>
     */
    public static final int SD_ONLY_VALUE = 0;
    /**
     * <code>SD_HD = 1;</code>
     */
    public static final int SD_HD_VALUE = 1;
    /**
     * <code>SD_UHD1 = 2;</code>
     */
    public static final int SD_UHD1_VALUE = 2;
    /**
     * <code>SD_UHD2 = 3;</code>
     */
    public static final int SD_UHD2_VALUE = 3;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static AllowedTracks valueOf(int value) {
      return forNumber(value);
    }

    public static AllowedTracks forNumber(int value) {
      switch (value) {
        case 0: return SD_ONLY;
        case 1: return SD_HD;
        case 2: return SD_UHD1;
        case 3: return SD_UHD2;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<AllowedTracks>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        AllowedTracks> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<AllowedTracks>() {
            public AllowedTracks findValueByNumber(int number) {
              return AllowedTracks.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.ua.mytrinity.tv_client.proto.DrmLink.getDescriptor().getEnumTypes().get(0);
    }

    private static final AllowedTracks[] VALUES = values();

    public static AllowedTracks valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private AllowedTracks(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:proto.AllowedTracks)
  }

  public interface DRMLinkOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.DRMLink)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string auth = 1;</code>
     */
    boolean hasAuth();
    /**
     * <code>required string auth = 1;</code>
     */
    java.lang.String getAuth();
    /**
     * <code>required string auth = 1;</code>
     */
    com.google.protobuf.ByteString
        getAuthBytes();

    /**
     * <code>required string content_id = 2;</code>
     */
    boolean hasContentId();
    /**
     * <code>required string content_id = 2;</code>
     */
    java.lang.String getContentId();
    /**
     * <code>required string content_id = 2;</code>
     */
    com.google.protobuf.ByteString
        getContentIdBytes();

    /**
     * <code>required .proto.AllowedTracks allowed_track_types = 3;</code>
     */
    boolean hasAllowedTrackTypes();
    /**
     * <code>required .proto.AllowedTracks allowed_track_types = 3;</code>
     */
    com.ua.mytrinity.tv_client.proto.DrmLink.AllowedTracks getAllowedTrackTypes();

    /**
     * <code>required uint32 ip = 4;</code>
     */
    boolean hasIp();
    /**
     * <code>required uint32 ip = 4;</code>
     */
    int getIp();

    /**
     * <code>required uint64 valid_until = 5;</code>
     */
    boolean hasValidUntil();
    /**
     * <code>required uint64 valid_until = 5;</code>
     */
    long getValidUntil();
  }
  /**
   * Protobuf type {@code proto.DRMLink}
   */
  public  static final class DRMLink extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.DRMLink)
      DRMLinkOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DRMLink.newBuilder() to construct.
    private DRMLink(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DRMLink() {
      auth_ = "";
      contentId_ = "";
      allowedTrackTypes_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DRMLink(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              auth_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              contentId_ = bs;
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              com.ua.mytrinity.tv_client.proto.DrmLink.AllowedTracks value = com.ua.mytrinity.tv_client.proto.DrmLink.AllowedTracks.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                allowedTrackTypes_ = rawValue;
              }
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              ip_ = input.readUInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              validUntil_ = input.readUInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ua.mytrinity.tv_client.proto.DrmLink.internal_static_proto_DRMLink_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ua.mytrinity.tv_client.proto.DrmLink.internal_static_proto_DRMLink_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ua.mytrinity.tv_client.proto.DrmLink.DRMLink.class, com.ua.mytrinity.tv_client.proto.DrmLink.DRMLink.Builder.class);
    }

    private int bitField0_;
    public static final int AUTH_FIELD_NUMBER = 1;
    private volatile java.lang.Object auth_;
    /**
     * <code>required string auth = 1;</code>
     */
    public boolean hasAuth() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required string auth = 1;</code>
     */
    public java.lang.String getAuth() {
      java.lang.Object ref = auth_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          auth_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string auth = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAuthBytes() {
      java.lang.Object ref = auth_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        auth_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONTENT_ID_FIELD_NUMBER = 2;
    private volatile java.lang.Object contentId_;
    /**
     * <code>required string content_id = 2;</code>
     */
    public boolean hasContentId() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required string content_id = 2;</code>
     */
    public java.lang.String getContentId() {
      java.lang.Object ref = contentId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          contentId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string content_id = 2;</code>
     */
    public com.google.protobuf.ByteString
        getContentIdBytes() {
      java.lang.Object ref = contentId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        contentId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ALLOWED_TRACK_TYPES_FIELD_NUMBER = 3;
    private int allowedTrackTypes_;
    /**
     * <code>required .proto.AllowedTracks allowed_track_types = 3;</code>
     */
    public boolean hasAllowedTrackTypes() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required .proto.AllowedTracks allowed_track_types = 3;</code>
     */
    public com.ua.mytrinity.tv_client.proto.DrmLink.AllowedTracks getAllowedTrackTypes() {
      @SuppressWarnings("deprecation")
      com.ua.mytrinity.tv_client.proto.DrmLink.AllowedTracks result = com.ua.mytrinity.tv_client.proto.DrmLink.AllowedTracks.valueOf(allowedTrackTypes_);
      return result == null ? com.ua.mytrinity.tv_client.proto.DrmLink.AllowedTracks.SD_ONLY : result;
    }

    public static final int IP_FIELD_NUMBER = 4;
    private int ip_;
    /**
     * <code>required uint32 ip = 4;</code>
     */
    public boolean hasIp() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>required uint32 ip = 4;</code>
     */
    public int getIp() {
      return ip_;
    }

    public static final int VALID_UNTIL_FIELD_NUMBER = 5;
    private long validUntil_;
    /**
     * <code>required uint64 valid_until = 5;</code>
     */
    public boolean hasValidUntil() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>required uint64 valid_until = 5;</code>
     */
    public long getValidUntil() {
      return validUntil_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasAuth()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasContentId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAllowedTrackTypes()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasValidUntil()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, auth_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, contentId_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeEnum(3, allowedTrackTypes_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeUInt32(4, ip_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeUInt64(5, validUntil_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, auth_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, contentId_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, allowedTrackTypes_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, ip_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(5, validUntil_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ua.mytrinity.tv_client.proto.DrmLink.DRMLink)) {
        return super.equals(obj);
      }
      com.ua.mytrinity.tv_client.proto.DrmLink.DRMLink other = (com.ua.mytrinity.tv_client.proto.DrmLink.DRMLink) obj;

      if (hasAuth() != other.hasAuth()) return false;
      if (hasAuth()) {
        if (!getAuth()
            .equals(other.getAuth())) return false;
      }
      if (hasContentId() != other.hasContentId()) return false;
      if (hasContentId()) {
        if (!getContentId()
            .equals(other.getContentId())) return false;
      }
      if (hasAllowedTrackTypes() != other.hasAllowedTrackTypes()) return false;
      if (hasAllowedTrackTypes()) {
        if (allowedTrackTypes_ != other.allowedTrackTypes_) return false;
      }
      if (hasIp() != other.hasIp()) return false;
      if (hasIp()) {
        if (getIp()
            != other.getIp()) return false;
      }
      if (hasValidUntil() != other.hasValidUntil()) return false;
      if (hasValidUntil()) {
        if (getValidUntil()
            != other.getValidUntil()) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasAuth()) {
        hash = (37 * hash) + AUTH_FIELD_NUMBER;
        hash = (53 * hash) + getAuth().hashCode();
      }
      if (hasContentId()) {
        hash = (37 * hash) + CONTENT_ID_FIELD_NUMBER;
        hash = (53 * hash) + getContentId().hashCode();
      }
      if (hasAllowedTrackTypes()) {
        hash = (37 * hash) + ALLOWED_TRACK_TYPES_FIELD_NUMBER;
        hash = (53 * hash) + allowedTrackTypes_;
      }
      if (hasIp()) {
        hash = (37 * hash) + IP_FIELD_NUMBER;
        hash = (53 * hash) + getIp();
      }
      if (hasValidUntil()) {
        hash = (37 * hash) + VALID_UNTIL_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getValidUntil());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ua.mytrinity.tv_client.proto.DrmLink.DRMLink parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ua.mytrinity.tv_client.proto.DrmLink.DRMLink parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ua.mytrinity.tv_client.proto.DrmLink.DRMLink parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ua.mytrinity.tv_client.proto.DrmLink.DRMLink parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ua.mytrinity.tv_client.proto.DrmLink.DRMLink parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ua.mytrinity.tv_client.proto.DrmLink.DRMLink parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ua.mytrinity.tv_client.proto.DrmLink.DRMLink parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ua.mytrinity.tv_client.proto.DrmLink.DRMLink parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ua.mytrinity.tv_client.proto.DrmLink.DRMLink parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ua.mytrinity.tv_client.proto.DrmLink.DRMLink parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ua.mytrinity.tv_client.proto.DrmLink.DRMLink parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ua.mytrinity.tv_client.proto.DrmLink.DRMLink parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ua.mytrinity.tv_client.proto.DrmLink.DRMLink prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.DRMLink}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.DRMLink)
        com.ua.mytrinity.tv_client.proto.DrmLink.DRMLinkOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ua.mytrinity.tv_client.proto.DrmLink.internal_static_proto_DRMLink_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ua.mytrinity.tv_client.proto.DrmLink.internal_static_proto_DRMLink_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ua.mytrinity.tv_client.proto.DrmLink.DRMLink.class, com.ua.mytrinity.tv_client.proto.DrmLink.DRMLink.Builder.class);
      }

      // Construct using com.ua.mytrinity.tv_client.proto.DrmLink.DRMLink.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        auth_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        contentId_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        allowedTrackTypes_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        ip_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        validUntil_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ua.mytrinity.tv_client.proto.DrmLink.internal_static_proto_DRMLink_descriptor;
      }

      @java.lang.Override
      public com.ua.mytrinity.tv_client.proto.DrmLink.DRMLink getDefaultInstanceForType() {
        return com.ua.mytrinity.tv_client.proto.DrmLink.DRMLink.getDefaultInstance();
      }

      @java.lang.Override
      public com.ua.mytrinity.tv_client.proto.DrmLink.DRMLink build() {
        com.ua.mytrinity.tv_client.proto.DrmLink.DRMLink result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.ua.mytrinity.tv_client.proto.DrmLink.DRMLink buildPartial() {
        com.ua.mytrinity.tv_client.proto.DrmLink.DRMLink result = new com.ua.mytrinity.tv_client.proto.DrmLink.DRMLink(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.auth_ = auth_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.contentId_ = contentId_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.allowedTrackTypes_ = allowedTrackTypes_;
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.ip_ = ip_;
          to_bitField0_ |= 0x00000008;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.validUntil_ = validUntil_;
          to_bitField0_ |= 0x00000010;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ua.mytrinity.tv_client.proto.DrmLink.DRMLink) {
          return mergeFrom((com.ua.mytrinity.tv_client.proto.DrmLink.DRMLink)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ua.mytrinity.tv_client.proto.DrmLink.DRMLink other) {
        if (other == com.ua.mytrinity.tv_client.proto.DrmLink.DRMLink.getDefaultInstance()) return this;
        if (other.hasAuth()) {
          bitField0_ |= 0x00000001;
          auth_ = other.auth_;
          onChanged();
        }
        if (other.hasContentId()) {
          bitField0_ |= 0x00000002;
          contentId_ = other.contentId_;
          onChanged();
        }
        if (other.hasAllowedTrackTypes()) {
          setAllowedTrackTypes(other.getAllowedTrackTypes());
        }
        if (other.hasIp()) {
          setIp(other.getIp());
        }
        if (other.hasValidUntil()) {
          setValidUntil(other.getValidUntil());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasAuth()) {
          return false;
        }
        if (!hasContentId()) {
          return false;
        }
        if (!hasAllowedTrackTypes()) {
          return false;
        }
        if (!hasIp()) {
          return false;
        }
        if (!hasValidUntil()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ua.mytrinity.tv_client.proto.DrmLink.DRMLink parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ua.mytrinity.tv_client.proto.DrmLink.DRMLink) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object auth_ = "";
      /**
       * <code>required string auth = 1;</code>
       */
      public boolean hasAuth() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required string auth = 1;</code>
       */
      public java.lang.String getAuth() {
        java.lang.Object ref = auth_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            auth_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string auth = 1;</code>
       */
      public com.google.protobuf.ByteString
          getAuthBytes() {
        java.lang.Object ref = auth_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          auth_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string auth = 1;</code>
       */
      public Builder setAuth(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        auth_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string auth = 1;</code>
       */
      public Builder clearAuth() {
        bitField0_ = (bitField0_ & ~0x00000001);
        auth_ = getDefaultInstance().getAuth();
        onChanged();
        return this;
      }
      /**
       * <code>required string auth = 1;</code>
       */
      public Builder setAuthBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        auth_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object contentId_ = "";
      /**
       * <code>required string content_id = 2;</code>
       */
      public boolean hasContentId() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required string content_id = 2;</code>
       */
      public java.lang.String getContentId() {
        java.lang.Object ref = contentId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            contentId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string content_id = 2;</code>
       */
      public com.google.protobuf.ByteString
          getContentIdBytes() {
        java.lang.Object ref = contentId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          contentId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string content_id = 2;</code>
       */
      public Builder setContentId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        contentId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string content_id = 2;</code>
       */
      public Builder clearContentId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        contentId_ = getDefaultInstance().getContentId();
        onChanged();
        return this;
      }
      /**
       * <code>required string content_id = 2;</code>
       */
      public Builder setContentIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        contentId_ = value;
        onChanged();
        return this;
      }

      private int allowedTrackTypes_ = 0;
      /**
       * <code>required .proto.AllowedTracks allowed_track_types = 3;</code>
       */
      public boolean hasAllowedTrackTypes() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>required .proto.AllowedTracks allowed_track_types = 3;</code>
       */
      public com.ua.mytrinity.tv_client.proto.DrmLink.AllowedTracks getAllowedTrackTypes() {
        @SuppressWarnings("deprecation")
        com.ua.mytrinity.tv_client.proto.DrmLink.AllowedTracks result = com.ua.mytrinity.tv_client.proto.DrmLink.AllowedTracks.valueOf(allowedTrackTypes_);
        return result == null ? com.ua.mytrinity.tv_client.proto.DrmLink.AllowedTracks.SD_ONLY : result;
      }
      /**
       * <code>required .proto.AllowedTracks allowed_track_types = 3;</code>
       */
      public Builder setAllowedTrackTypes(com.ua.mytrinity.tv_client.proto.DrmLink.AllowedTracks value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        allowedTrackTypes_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .proto.AllowedTracks allowed_track_types = 3;</code>
       */
      public Builder clearAllowedTrackTypes() {
        bitField0_ = (bitField0_ & ~0x00000004);
        allowedTrackTypes_ = 0;
        onChanged();
        return this;
      }

      private int ip_ ;
      /**
       * <code>required uint32 ip = 4;</code>
       */
      public boolean hasIp() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>required uint32 ip = 4;</code>
       */
      public int getIp() {
        return ip_;
      }
      /**
       * <code>required uint32 ip = 4;</code>
       */
      public Builder setIp(int value) {
        bitField0_ |= 0x00000008;
        ip_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 ip = 4;</code>
       */
      public Builder clearIp() {
        bitField0_ = (bitField0_ & ~0x00000008);
        ip_ = 0;
        onChanged();
        return this;
      }

      private long validUntil_ ;
      /**
       * <code>required uint64 valid_until = 5;</code>
       */
      public boolean hasValidUntil() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>required uint64 valid_until = 5;</code>
       */
      public long getValidUntil() {
        return validUntil_;
      }
      /**
       * <code>required uint64 valid_until = 5;</code>
       */
      public Builder setValidUntil(long value) {
        bitField0_ |= 0x00000010;
        validUntil_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint64 valid_until = 5;</code>
       */
      public Builder clearValidUntil() {
        bitField0_ = (bitField0_ & ~0x00000010);
        validUntil_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.DRMLink)
    }

    // @@protoc_insertion_point(class_scope:proto.DRMLink)
    private static final com.ua.mytrinity.tv_client.proto.DrmLink.DRMLink DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ua.mytrinity.tv_client.proto.DrmLink.DRMLink();
    }

    public static com.ua.mytrinity.tv_client.proto.DrmLink.DRMLink getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<DRMLink>
        PARSER = new com.google.protobuf.AbstractParser<DRMLink>() {
      @java.lang.Override
      public DRMLink parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DRMLink(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DRMLink> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DRMLink> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.ua.mytrinity.tv_client.proto.DrmLink.DRMLink getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_DRMLink_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_DRMLink_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016drm_link.proto\022\005proto\"\177\n\007DRMLink\022\014\n\004au" +
      "th\030\001 \002(\t\022\022\n\ncontent_id\030\002 \002(\t\0221\n\023allowed_" +
      "track_types\030\003 \002(\0162\024.proto.AllowedTracks\022" +
      "\n\n\002ip\030\004 \002(\r\022\023\n\013valid_until\030\005 \002(\004*A\n\rAllo" +
      "wedTracks\022\013\n\007SD_ONLY\020\000\022\t\n\005SD_HD\020\001\022\013\n\007SD_" +
      "UHD1\020\002\022\013\n\007SD_UHD2\020\003B\"\n com.ua.mytrinity." +
      "tv_client.proto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_proto_DRMLink_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_DRMLink_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_DRMLink_descriptor,
        new java.lang.String[] { "Auth", "ContentId", "AllowedTrackTypes", "Ip", "ValidUntil", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
