// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: geo.proto

package com.ua.mytrinity.tv_client.proto;

public final class GeoProto {
  private GeoProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CountryOrBuilder extends
      // @@protoc_insertion_point(interface_extends:geo.Country)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>required string code = 2;</code>
     */
    boolean hasCode();
    /**
     * <code>required string code = 2;</code>
     */
    java.lang.String getCode();
    /**
     * <code>required string code = 2;</code>
     */
    com.google.protobuf.ByteString
        getCodeBytes();

    /**
     * <code>optional string name = 3;</code>
     */
    boolean hasName();
    /**
     * <code>optional string name = 3;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 3;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional int32 geoname_id = 4;</code>
     */
    boolean hasGeonameId();
    /**
     * <code>optional int32 geoname_id = 4;</code>
     */
    int getGeonameId();

    /**
     * <code>optional int32 telephone_code = 5;</code>
     */
    boolean hasTelephoneCode();
    /**
     * <code>optional int32 telephone_code = 5;</code>
     */
    int getTelephoneCode();

    /**
     * <code>optional string currency = 6;</code>
     */
    boolean hasCurrency();
    /**
     * <code>optional string currency = 6;</code>
     */
    java.lang.String getCurrency();
    /**
     * <code>optional string currency = 6;</code>
     */
    com.google.protobuf.ByteString
        getCurrencyBytes();

    /**
     * <code>optional int32 size_of_nsn = 7;</code>
     */
    boolean hasSizeOfNsn();
    /**
     * <code>optional int32 size_of_nsn = 7;</code>
     */
    int getSizeOfNsn();
  }
  /**
   * Protobuf type {@code geo.Country}
   */
  public  static final class Country extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:geo.Country)
      CountryOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Country.newBuilder() to construct.
    private Country(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Country() {
      code_ = "";
      name_ = "";
      currency_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Country(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              code_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              name_ = bs;
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              geonameId_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              telephoneCode_ = input.readInt32();
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              currency_ = bs;
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              sizeOfNsn_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ua.mytrinity.tv_client.proto.GeoProto.internal_static_geo_Country_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ua.mytrinity.tv_client.proto.GeoProto.internal_static_geo_Country_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ua.mytrinity.tv_client.proto.GeoProto.Country.class, com.ua.mytrinity.tv_client.proto.GeoProto.Country.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>required int32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int CODE_FIELD_NUMBER = 2;
    private volatile java.lang.Object code_;
    /**
     * <code>required string code = 2;</code>
     */
    public boolean hasCode() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required string code = 2;</code>
     */
    public java.lang.String getCode() {
      java.lang.Object ref = code_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          code_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string code = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCodeBytes() {
      java.lang.Object ref = code_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        code_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object name_;
    /**
     * <code>optional string name = 3;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string name = 3;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string name = 3;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GEONAME_ID_FIELD_NUMBER = 4;
    private int geonameId_;
    /**
     * <code>optional int32 geoname_id = 4;</code>
     */
    public boolean hasGeonameId() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional int32 geoname_id = 4;</code>
     */
    public int getGeonameId() {
      return geonameId_;
    }

    public static final int TELEPHONE_CODE_FIELD_NUMBER = 5;
    private int telephoneCode_;
    /**
     * <code>optional int32 telephone_code = 5;</code>
     */
    public boolean hasTelephoneCode() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional int32 telephone_code = 5;</code>
     */
    public int getTelephoneCode() {
      return telephoneCode_;
    }

    public static final int CURRENCY_FIELD_NUMBER = 6;
    private volatile java.lang.Object currency_;
    /**
     * <code>optional string currency = 6;</code>
     */
    public boolean hasCurrency() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional string currency = 6;</code>
     */
    public java.lang.String getCurrency() {
      java.lang.Object ref = currency_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          currency_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string currency = 6;</code>
     */
    public com.google.protobuf.ByteString
        getCurrencyBytes() {
      java.lang.Object ref = currency_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        currency_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SIZE_OF_NSN_FIELD_NUMBER = 7;
    private int sizeOfNsn_;
    /**
     * <code>optional int32 size_of_nsn = 7;</code>
     */
    public boolean hasSizeOfNsn() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>optional int32 size_of_nsn = 7;</code>
     */
    public int getSizeOfNsn() {
      return sizeOfNsn_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, code_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, name_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeInt32(4, geonameId_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeInt32(5, telephoneCode_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, currency_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        output.writeInt32(7, sizeOfNsn_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, code_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, name_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, geonameId_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, telephoneCode_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, currency_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, sizeOfNsn_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ua.mytrinity.tv_client.proto.GeoProto.Country)) {
        return super.equals(obj);
      }
      com.ua.mytrinity.tv_client.proto.GeoProto.Country other = (com.ua.mytrinity.tv_client.proto.GeoProto.Country) obj;

      if (hasId() != other.hasId()) return false;
      if (hasId()) {
        if (getId()
            != other.getId()) return false;
      }
      if (hasCode() != other.hasCode()) return false;
      if (hasCode()) {
        if (!getCode()
            .equals(other.getCode())) return false;
      }
      if (hasName() != other.hasName()) return false;
      if (hasName()) {
        if (!getName()
            .equals(other.getName())) return false;
      }
      if (hasGeonameId() != other.hasGeonameId()) return false;
      if (hasGeonameId()) {
        if (getGeonameId()
            != other.getGeonameId()) return false;
      }
      if (hasTelephoneCode() != other.hasTelephoneCode()) return false;
      if (hasTelephoneCode()) {
        if (getTelephoneCode()
            != other.getTelephoneCode()) return false;
      }
      if (hasCurrency() != other.hasCurrency()) return false;
      if (hasCurrency()) {
        if (!getCurrency()
            .equals(other.getCurrency())) return false;
      }
      if (hasSizeOfNsn() != other.hasSizeOfNsn()) return false;
      if (hasSizeOfNsn()) {
        if (getSizeOfNsn()
            != other.getSizeOfNsn()) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId();
      }
      if (hasCode()) {
        hash = (37 * hash) + CODE_FIELD_NUMBER;
        hash = (53 * hash) + getCode().hashCode();
      }
      if (hasName()) {
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
      }
      if (hasGeonameId()) {
        hash = (37 * hash) + GEONAME_ID_FIELD_NUMBER;
        hash = (53 * hash) + getGeonameId();
      }
      if (hasTelephoneCode()) {
        hash = (37 * hash) + TELEPHONE_CODE_FIELD_NUMBER;
        hash = (53 * hash) + getTelephoneCode();
      }
      if (hasCurrency()) {
        hash = (37 * hash) + CURRENCY_FIELD_NUMBER;
        hash = (53 * hash) + getCurrency().hashCode();
      }
      if (hasSizeOfNsn()) {
        hash = (37 * hash) + SIZE_OF_NSN_FIELD_NUMBER;
        hash = (53 * hash) + getSizeOfNsn();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ua.mytrinity.tv_client.proto.GeoProto.Country parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ua.mytrinity.tv_client.proto.GeoProto.Country parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ua.mytrinity.tv_client.proto.GeoProto.Country parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ua.mytrinity.tv_client.proto.GeoProto.Country parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ua.mytrinity.tv_client.proto.GeoProto.Country parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ua.mytrinity.tv_client.proto.GeoProto.Country parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ua.mytrinity.tv_client.proto.GeoProto.Country parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ua.mytrinity.tv_client.proto.GeoProto.Country parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ua.mytrinity.tv_client.proto.GeoProto.Country parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ua.mytrinity.tv_client.proto.GeoProto.Country parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ua.mytrinity.tv_client.proto.GeoProto.Country parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ua.mytrinity.tv_client.proto.GeoProto.Country parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ua.mytrinity.tv_client.proto.GeoProto.Country prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code geo.Country}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:geo.Country)
        com.ua.mytrinity.tv_client.proto.GeoProto.CountryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ua.mytrinity.tv_client.proto.GeoProto.internal_static_geo_Country_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ua.mytrinity.tv_client.proto.GeoProto.internal_static_geo_Country_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ua.mytrinity.tv_client.proto.GeoProto.Country.class, com.ua.mytrinity.tv_client.proto.GeoProto.Country.Builder.class);
      }

      // Construct using com.ua.mytrinity.tv_client.proto.GeoProto.Country.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        code_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        geonameId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        telephoneCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        currency_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        sizeOfNsn_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ua.mytrinity.tv_client.proto.GeoProto.internal_static_geo_Country_descriptor;
      }

      @java.lang.Override
      public com.ua.mytrinity.tv_client.proto.GeoProto.Country getDefaultInstanceForType() {
        return com.ua.mytrinity.tv_client.proto.GeoProto.Country.getDefaultInstance();
      }

      @java.lang.Override
      public com.ua.mytrinity.tv_client.proto.GeoProto.Country build() {
        com.ua.mytrinity.tv_client.proto.GeoProto.Country result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.ua.mytrinity.tv_client.proto.GeoProto.Country buildPartial() {
        com.ua.mytrinity.tv_client.proto.GeoProto.Country result = new com.ua.mytrinity.tv_client.proto.GeoProto.Country(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.code_ = code_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.geonameId_ = geonameId_;
          to_bitField0_ |= 0x00000008;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.telephoneCode_ = telephoneCode_;
          to_bitField0_ |= 0x00000010;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          to_bitField0_ |= 0x00000020;
        }
        result.currency_ = currency_;
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.sizeOfNsn_ = sizeOfNsn_;
          to_bitField0_ |= 0x00000040;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ua.mytrinity.tv_client.proto.GeoProto.Country) {
          return mergeFrom((com.ua.mytrinity.tv_client.proto.GeoProto.Country)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ua.mytrinity.tv_client.proto.GeoProto.Country other) {
        if (other == com.ua.mytrinity.tv_client.proto.GeoProto.Country.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasCode()) {
          bitField0_ |= 0x00000002;
          code_ = other.code_;
          onChanged();
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000004;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasGeonameId()) {
          setGeonameId(other.getGeonameId());
        }
        if (other.hasTelephoneCode()) {
          setTelephoneCode(other.getTelephoneCode());
        }
        if (other.hasCurrency()) {
          bitField0_ |= 0x00000020;
          currency_ = other.currency_;
          onChanged();
        }
        if (other.hasSizeOfNsn()) {
          setSizeOfNsn(other.getSizeOfNsn());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasId()) {
          return false;
        }
        if (!hasCode()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ua.mytrinity.tv_client.proto.GeoProto.Country parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ua.mytrinity.tv_client.proto.GeoProto.Country) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>required int32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object code_ = "";
      /**
       * <code>required string code = 2;</code>
       */
      public boolean hasCode() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required string code = 2;</code>
       */
      public java.lang.String getCode() {
        java.lang.Object ref = code_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            code_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string code = 2;</code>
       */
      public com.google.protobuf.ByteString
          getCodeBytes() {
        java.lang.Object ref = code_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          code_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string code = 2;</code>
       */
      public Builder setCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string code = 2;</code>
       */
      public Builder clearCode() {
        bitField0_ = (bitField0_ & ~0x00000002);
        code_ = getDefaultInstance().getCode();
        onChanged();
        return this;
      }
      /**
       * <code>required string code = 2;</code>
       */
      public Builder setCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        code_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 3;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional string name = 3;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 3;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 3;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 3;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000004);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 3;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        name_ = value;
        onChanged();
        return this;
      }

      private int geonameId_ ;
      /**
       * <code>optional int32 geoname_id = 4;</code>
       */
      public boolean hasGeonameId() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional int32 geoname_id = 4;</code>
       */
      public int getGeonameId() {
        return geonameId_;
      }
      /**
       * <code>optional int32 geoname_id = 4;</code>
       */
      public Builder setGeonameId(int value) {
        bitField0_ |= 0x00000008;
        geonameId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 geoname_id = 4;</code>
       */
      public Builder clearGeonameId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        geonameId_ = 0;
        onChanged();
        return this;
      }

      private int telephoneCode_ ;
      /**
       * <code>optional int32 telephone_code = 5;</code>
       */
      public boolean hasTelephoneCode() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>optional int32 telephone_code = 5;</code>
       */
      public int getTelephoneCode() {
        return telephoneCode_;
      }
      /**
       * <code>optional int32 telephone_code = 5;</code>
       */
      public Builder setTelephoneCode(int value) {
        bitField0_ |= 0x00000010;
        telephoneCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 telephone_code = 5;</code>
       */
      public Builder clearTelephoneCode() {
        bitField0_ = (bitField0_ & ~0x00000010);
        telephoneCode_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object currency_ = "";
      /**
       * <code>optional string currency = 6;</code>
       */
      public boolean hasCurrency() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>optional string currency = 6;</code>
       */
      public java.lang.String getCurrency() {
        java.lang.Object ref = currency_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            currency_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string currency = 6;</code>
       */
      public com.google.protobuf.ByteString
          getCurrencyBytes() {
        java.lang.Object ref = currency_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          currency_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string currency = 6;</code>
       */
      public Builder setCurrency(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        currency_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string currency = 6;</code>
       */
      public Builder clearCurrency() {
        bitField0_ = (bitField0_ & ~0x00000020);
        currency_ = getDefaultInstance().getCurrency();
        onChanged();
        return this;
      }
      /**
       * <code>optional string currency = 6;</code>
       */
      public Builder setCurrencyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        currency_ = value;
        onChanged();
        return this;
      }

      private int sizeOfNsn_ ;
      /**
       * <code>optional int32 size_of_nsn = 7;</code>
       */
      public boolean hasSizeOfNsn() {
        return ((bitField0_ & 0x00000040) != 0);
      }
      /**
       * <code>optional int32 size_of_nsn = 7;</code>
       */
      public int getSizeOfNsn() {
        return sizeOfNsn_;
      }
      /**
       * <code>optional int32 size_of_nsn = 7;</code>
       */
      public Builder setSizeOfNsn(int value) {
        bitField0_ |= 0x00000040;
        sizeOfNsn_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 size_of_nsn = 7;</code>
       */
      public Builder clearSizeOfNsn() {
        bitField0_ = (bitField0_ & ~0x00000040);
        sizeOfNsn_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:geo.Country)
    }

    // @@protoc_insertion_point(class_scope:geo.Country)
    private static final com.ua.mytrinity.tv_client.proto.GeoProto.Country DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ua.mytrinity.tv_client.proto.GeoProto.Country();
    }

    public static com.ua.mytrinity.tv_client.proto.GeoProto.Country getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Country>
        PARSER = new com.google.protobuf.AbstractParser<Country>() {
      @java.lang.Override
      public Country parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Country(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Country> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Country> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.ua.mytrinity.tv_client.proto.GeoProto.Country getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_geo_Country_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_geo_Country_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tgeo.proto\022\003geo\"\204\001\n\007Country\022\n\n\002id\030\001 \002(\005" +
      "\022\014\n\004code\030\002 \002(\t\022\014\n\004name\030\003 \001(\t\022\022\n\ngeoname_" +
      "id\030\004 \001(\005\022\026\n\016telephone_code\030\005 \001(\005\022\020\n\010curr" +
      "ency\030\006 \001(\t\022\023\n\013size_of_nsn\030\007 \001(\005B,\n com.u" +
      "a.mytrinity.tv_client.protoB\010GeoProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_geo_Country_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_geo_Country_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_geo_Country_descriptor,
        new java.lang.String[] { "Id", "Code", "Name", "GeonameId", "TelephoneCode", "Currency", "SizeOfNsn", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
