// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: search.proto

package com.ua.mytrinity.tv_client.proto;

public final class Search {
  private Search() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SearchResultRecordOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.SearchResultRecord)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .proto.SearchResultRecord.RecordType type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>optional .proto.SearchResultRecord.RecordType type = 1;</code>
     */
    com.ua.mytrinity.tv_client.proto.Search.SearchResultRecord.RecordType getType();

    /**
     * <code>repeated int32 id_list = 2;</code>
     */
    java.util.List<java.lang.Integer> getIdListList();
    /**
     * <code>repeated int32 id_list = 2;</code>
     */
    int getIdListCount();
    /**
     * <code>repeated int32 id_list = 2;</code>
     */
    int getIdList(int index);
  }
  /**
   * Protobuf type {@code proto.SearchResultRecord}
   */
  public  static final class SearchResultRecord extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.SearchResultRecord)
      SearchResultRecordOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SearchResultRecord.newBuilder() to construct.
    private SearchResultRecord(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SearchResultRecord() {
      type_ = 0;
      idList_ = emptyIntList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SearchResultRecord(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              com.ua.mytrinity.tv_client.proto.Search.SearchResultRecord.RecordType value = com.ua.mytrinity.tv_client.proto.Search.SearchResultRecord.RecordType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = rawValue;
              }
              break;
            }
            case 16: {
              if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                idList_ = newIntList();
                mutable_bitField0_ |= 0x00000002;
              }
              idList_.addInt(input.readInt32());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000002) != 0) && input.getBytesUntilLimit() > 0) {
                idList_ = newIntList();
                mutable_bitField0_ |= 0x00000002;
              }
              while (input.getBytesUntilLimit() > 0) {
                idList_.addInt(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) != 0)) {
          idList_.makeImmutable(); // C
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ua.mytrinity.tv_client.proto.Search.internal_static_proto_SearchResultRecord_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ua.mytrinity.tv_client.proto.Search.internal_static_proto_SearchResultRecord_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ua.mytrinity.tv_client.proto.Search.SearchResultRecord.class, com.ua.mytrinity.tv_client.proto.Search.SearchResultRecord.Builder.class);
    }

    /**
     * Protobuf enum {@code proto.SearchResultRecord.RecordType}
     */
    public enum RecordType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>Movie = 0;</code>
       */
      Movie(0),
      /**
       * <code>Channel = 1;</code>
       */
      Channel(1),
      /**
       * <code>EpgRecord = 2;</code>
       */
      EpgRecord(2),
      /**
       * <code>News = 3;</code>
       */
      News(3),
      ;

      /**
       * <code>Movie = 0;</code>
       */
      public static final int Movie_VALUE = 0;
      /**
       * <code>Channel = 1;</code>
       */
      public static final int Channel_VALUE = 1;
      /**
       * <code>EpgRecord = 2;</code>
       */
      public static final int EpgRecord_VALUE = 2;
      /**
       * <code>News = 3;</code>
       */
      public static final int News_VALUE = 3;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static RecordType valueOf(int value) {
        return forNumber(value);
      }

      public static RecordType forNumber(int value) {
        switch (value) {
          case 0: return Movie;
          case 1: return Channel;
          case 2: return EpgRecord;
          case 3: return News;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<RecordType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          RecordType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<RecordType>() {
              public RecordType findValueByNumber(int number) {
                return RecordType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.ua.mytrinity.tv_client.proto.Search.SearchResultRecord.getDescriptor().getEnumTypes().get(0);
      }

      private static final RecordType[] VALUES = values();

      public static RecordType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private RecordType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:proto.SearchResultRecord.RecordType)
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>optional .proto.SearchResultRecord.RecordType type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional .proto.SearchResultRecord.RecordType type = 1;</code>
     */
    public com.ua.mytrinity.tv_client.proto.Search.SearchResultRecord.RecordType getType() {
      @SuppressWarnings("deprecation")
      com.ua.mytrinity.tv_client.proto.Search.SearchResultRecord.RecordType result = com.ua.mytrinity.tv_client.proto.Search.SearchResultRecord.RecordType.valueOf(type_);
      return result == null ? com.ua.mytrinity.tv_client.proto.Search.SearchResultRecord.RecordType.Movie : result;
    }

    public static final int ID_LIST_FIELD_NUMBER = 2;
    private com.google.protobuf.Internal.IntList idList_;
    /**
     * <code>repeated int32 id_list = 2;</code>
     */
    public java.util.List<java.lang.Integer>
        getIdListList() {
      return idList_;
    }
    /**
     * <code>repeated int32 id_list = 2;</code>
     */
    public int getIdListCount() {
      return idList_.size();
    }
    /**
     * <code>repeated int32 id_list = 2;</code>
     */
    public int getIdList(int index) {
      return idList_.getInt(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeEnum(1, type_);
      }
      for (int i = 0; i < idList_.size(); i++) {
        output.writeInt32(2, idList_.getInt(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < idList_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(idList_.getInt(i));
        }
        size += dataSize;
        size += 1 * getIdListList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ua.mytrinity.tv_client.proto.Search.SearchResultRecord)) {
        return super.equals(obj);
      }
      com.ua.mytrinity.tv_client.proto.Search.SearchResultRecord other = (com.ua.mytrinity.tv_client.proto.Search.SearchResultRecord) obj;

      if (hasType() != other.hasType()) return false;
      if (hasType()) {
        if (type_ != other.type_) return false;
      }
      if (!getIdListList()
          .equals(other.getIdListList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasType()) {
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + type_;
      }
      if (getIdListCount() > 0) {
        hash = (37 * hash) + ID_LIST_FIELD_NUMBER;
        hash = (53 * hash) + getIdListList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ua.mytrinity.tv_client.proto.Search.SearchResultRecord parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ua.mytrinity.tv_client.proto.Search.SearchResultRecord parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ua.mytrinity.tv_client.proto.Search.SearchResultRecord parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ua.mytrinity.tv_client.proto.Search.SearchResultRecord parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ua.mytrinity.tv_client.proto.Search.SearchResultRecord parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ua.mytrinity.tv_client.proto.Search.SearchResultRecord parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ua.mytrinity.tv_client.proto.Search.SearchResultRecord parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ua.mytrinity.tv_client.proto.Search.SearchResultRecord parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ua.mytrinity.tv_client.proto.Search.SearchResultRecord parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ua.mytrinity.tv_client.proto.Search.SearchResultRecord parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ua.mytrinity.tv_client.proto.Search.SearchResultRecord parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ua.mytrinity.tv_client.proto.Search.SearchResultRecord parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ua.mytrinity.tv_client.proto.Search.SearchResultRecord prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.SearchResultRecord}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.SearchResultRecord)
        com.ua.mytrinity.tv_client.proto.Search.SearchResultRecordOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ua.mytrinity.tv_client.proto.Search.internal_static_proto_SearchResultRecord_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ua.mytrinity.tv_client.proto.Search.internal_static_proto_SearchResultRecord_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ua.mytrinity.tv_client.proto.Search.SearchResultRecord.class, com.ua.mytrinity.tv_client.proto.Search.SearchResultRecord.Builder.class);
      }

      // Construct using com.ua.mytrinity.tv_client.proto.Search.SearchResultRecord.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        idList_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ua.mytrinity.tv_client.proto.Search.internal_static_proto_SearchResultRecord_descriptor;
      }

      @java.lang.Override
      public com.ua.mytrinity.tv_client.proto.Search.SearchResultRecord getDefaultInstanceForType() {
        return com.ua.mytrinity.tv_client.proto.Search.SearchResultRecord.getDefaultInstance();
      }

      @java.lang.Override
      public com.ua.mytrinity.tv_client.proto.Search.SearchResultRecord build() {
        com.ua.mytrinity.tv_client.proto.Search.SearchResultRecord result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.ua.mytrinity.tv_client.proto.Search.SearchResultRecord buildPartial() {
        com.ua.mytrinity.tv_client.proto.Search.SearchResultRecord result = new com.ua.mytrinity.tv_client.proto.Search.SearchResultRecord(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((bitField0_ & 0x00000002) != 0)) {
          idList_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.idList_ = idList_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ua.mytrinity.tv_client.proto.Search.SearchResultRecord) {
          return mergeFrom((com.ua.mytrinity.tv_client.proto.Search.SearchResultRecord)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ua.mytrinity.tv_client.proto.Search.SearchResultRecord other) {
        if (other == com.ua.mytrinity.tv_client.proto.Search.SearchResultRecord.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (!other.idList_.isEmpty()) {
          if (idList_.isEmpty()) {
            idList_ = other.idList_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureIdListIsMutable();
            idList_.addAll(other.idList_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ua.mytrinity.tv_client.proto.Search.SearchResultRecord parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ua.mytrinity.tv_client.proto.Search.SearchResultRecord) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int type_ = 0;
      /**
       * <code>optional .proto.SearchResultRecord.RecordType type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional .proto.SearchResultRecord.RecordType type = 1;</code>
       */
      public com.ua.mytrinity.tv_client.proto.Search.SearchResultRecord.RecordType getType() {
        @SuppressWarnings("deprecation")
        com.ua.mytrinity.tv_client.proto.Search.SearchResultRecord.RecordType result = com.ua.mytrinity.tv_client.proto.Search.SearchResultRecord.RecordType.valueOf(type_);
        return result == null ? com.ua.mytrinity.tv_client.proto.Search.SearchResultRecord.RecordType.Movie : result;
      }
      /**
       * <code>optional .proto.SearchResultRecord.RecordType type = 1;</code>
       */
      public Builder setType(com.ua.mytrinity.tv_client.proto.Search.SearchResultRecord.RecordType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .proto.SearchResultRecord.RecordType type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.IntList idList_ = emptyIntList();
      private void ensureIdListIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          idList_ = mutableCopy(idList_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated int32 id_list = 2;</code>
       */
      public java.util.List<java.lang.Integer>
          getIdListList() {
        return ((bitField0_ & 0x00000002) != 0) ?
                 java.util.Collections.unmodifiableList(idList_) : idList_;
      }
      /**
       * <code>repeated int32 id_list = 2;</code>
       */
      public int getIdListCount() {
        return idList_.size();
      }
      /**
       * <code>repeated int32 id_list = 2;</code>
       */
      public int getIdList(int index) {
        return idList_.getInt(index);
      }
      /**
       * <code>repeated int32 id_list = 2;</code>
       */
      public Builder setIdList(
          int index, int value) {
        ensureIdListIsMutable();
        idList_.setInt(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 id_list = 2;</code>
       */
      public Builder addIdList(int value) {
        ensureIdListIsMutable();
        idList_.addInt(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 id_list = 2;</code>
       */
      public Builder addAllIdList(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureIdListIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, idList_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 id_list = 2;</code>
       */
      public Builder clearIdList() {
        idList_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.SearchResultRecord)
    }

    // @@protoc_insertion_point(class_scope:proto.SearchResultRecord)
    private static final com.ua.mytrinity.tv_client.proto.Search.SearchResultRecord DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ua.mytrinity.tv_client.proto.Search.SearchResultRecord();
    }

    public static com.ua.mytrinity.tv_client.proto.Search.SearchResultRecord getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<SearchResultRecord>
        PARSER = new com.google.protobuf.AbstractParser<SearchResultRecord>() {
      @java.lang.Override
      public SearchResultRecord parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SearchResultRecord(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SearchResultRecord> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SearchResultRecord> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.ua.mytrinity.tv_client.proto.Search.SearchResultRecord getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SuperSearchRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.SuperSearchRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string auth = 1;</code>
     */
    boolean hasAuth();
    /**
     * <code>required string auth = 1;</code>
     */
    java.lang.String getAuth();
    /**
     * <code>required string auth = 1;</code>
     */
    com.google.protobuf.ByteString
        getAuthBytes();

    /**
     * <code>optional string needle = 2;</code>
     */
    boolean hasNeedle();
    /**
     * <code>optional string needle = 2;</code>
     */
    java.lang.String getNeedle();
    /**
     * <code>optional string needle = 2;</code>
     */
    com.google.protobuf.ByteString
        getNeedleBytes();
  }
  /**
   * Protobuf type {@code proto.SuperSearchRequest}
   */
  public  static final class SuperSearchRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.SuperSearchRequest)
      SuperSearchRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SuperSearchRequest.newBuilder() to construct.
    private SuperSearchRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SuperSearchRequest() {
      auth_ = "";
      needle_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SuperSearchRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              auth_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              needle_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ua.mytrinity.tv_client.proto.Search.internal_static_proto_SuperSearchRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ua.mytrinity.tv_client.proto.Search.internal_static_proto_SuperSearchRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ua.mytrinity.tv_client.proto.Search.SuperSearchRequest.class, com.ua.mytrinity.tv_client.proto.Search.SuperSearchRequest.Builder.class);
    }

    private int bitField0_;
    public static final int AUTH_FIELD_NUMBER = 1;
    private volatile java.lang.Object auth_;
    /**
     * <code>required string auth = 1;</code>
     */
    public boolean hasAuth() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required string auth = 1;</code>
     */
    public java.lang.String getAuth() {
      java.lang.Object ref = auth_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          auth_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string auth = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAuthBytes() {
      java.lang.Object ref = auth_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        auth_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NEEDLE_FIELD_NUMBER = 2;
    private volatile java.lang.Object needle_;
    /**
     * <code>optional string needle = 2;</code>
     */
    public boolean hasNeedle() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string needle = 2;</code>
     */
    public java.lang.String getNeedle() {
      java.lang.Object ref = needle_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          needle_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string needle = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNeedleBytes() {
      java.lang.Object ref = needle_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        needle_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasAuth()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, auth_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, needle_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, auth_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, needle_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ua.mytrinity.tv_client.proto.Search.SuperSearchRequest)) {
        return super.equals(obj);
      }
      com.ua.mytrinity.tv_client.proto.Search.SuperSearchRequest other = (com.ua.mytrinity.tv_client.proto.Search.SuperSearchRequest) obj;

      if (hasAuth() != other.hasAuth()) return false;
      if (hasAuth()) {
        if (!getAuth()
            .equals(other.getAuth())) return false;
      }
      if (hasNeedle() != other.hasNeedle()) return false;
      if (hasNeedle()) {
        if (!getNeedle()
            .equals(other.getNeedle())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasAuth()) {
        hash = (37 * hash) + AUTH_FIELD_NUMBER;
        hash = (53 * hash) + getAuth().hashCode();
      }
      if (hasNeedle()) {
        hash = (37 * hash) + NEEDLE_FIELD_NUMBER;
        hash = (53 * hash) + getNeedle().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ua.mytrinity.tv_client.proto.Search.SuperSearchRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ua.mytrinity.tv_client.proto.Search.SuperSearchRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ua.mytrinity.tv_client.proto.Search.SuperSearchRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ua.mytrinity.tv_client.proto.Search.SuperSearchRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ua.mytrinity.tv_client.proto.Search.SuperSearchRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ua.mytrinity.tv_client.proto.Search.SuperSearchRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ua.mytrinity.tv_client.proto.Search.SuperSearchRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ua.mytrinity.tv_client.proto.Search.SuperSearchRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ua.mytrinity.tv_client.proto.Search.SuperSearchRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ua.mytrinity.tv_client.proto.Search.SuperSearchRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ua.mytrinity.tv_client.proto.Search.SuperSearchRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ua.mytrinity.tv_client.proto.Search.SuperSearchRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ua.mytrinity.tv_client.proto.Search.SuperSearchRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.SuperSearchRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.SuperSearchRequest)
        com.ua.mytrinity.tv_client.proto.Search.SuperSearchRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ua.mytrinity.tv_client.proto.Search.internal_static_proto_SuperSearchRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ua.mytrinity.tv_client.proto.Search.internal_static_proto_SuperSearchRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ua.mytrinity.tv_client.proto.Search.SuperSearchRequest.class, com.ua.mytrinity.tv_client.proto.Search.SuperSearchRequest.Builder.class);
      }

      // Construct using com.ua.mytrinity.tv_client.proto.Search.SuperSearchRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        auth_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        needle_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ua.mytrinity.tv_client.proto.Search.internal_static_proto_SuperSearchRequest_descriptor;
      }

      @java.lang.Override
      public com.ua.mytrinity.tv_client.proto.Search.SuperSearchRequest getDefaultInstanceForType() {
        return com.ua.mytrinity.tv_client.proto.Search.SuperSearchRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.ua.mytrinity.tv_client.proto.Search.SuperSearchRequest build() {
        com.ua.mytrinity.tv_client.proto.Search.SuperSearchRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.ua.mytrinity.tv_client.proto.Search.SuperSearchRequest buildPartial() {
        com.ua.mytrinity.tv_client.proto.Search.SuperSearchRequest result = new com.ua.mytrinity.tv_client.proto.Search.SuperSearchRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.auth_ = auth_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.needle_ = needle_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ua.mytrinity.tv_client.proto.Search.SuperSearchRequest) {
          return mergeFrom((com.ua.mytrinity.tv_client.proto.Search.SuperSearchRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ua.mytrinity.tv_client.proto.Search.SuperSearchRequest other) {
        if (other == com.ua.mytrinity.tv_client.proto.Search.SuperSearchRequest.getDefaultInstance()) return this;
        if (other.hasAuth()) {
          bitField0_ |= 0x00000001;
          auth_ = other.auth_;
          onChanged();
        }
        if (other.hasNeedle()) {
          bitField0_ |= 0x00000002;
          needle_ = other.needle_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasAuth()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ua.mytrinity.tv_client.proto.Search.SuperSearchRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ua.mytrinity.tv_client.proto.Search.SuperSearchRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object auth_ = "";
      /**
       * <code>required string auth = 1;</code>
       */
      public boolean hasAuth() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required string auth = 1;</code>
       */
      public java.lang.String getAuth() {
        java.lang.Object ref = auth_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            auth_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string auth = 1;</code>
       */
      public com.google.protobuf.ByteString
          getAuthBytes() {
        java.lang.Object ref = auth_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          auth_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string auth = 1;</code>
       */
      public Builder setAuth(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        auth_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string auth = 1;</code>
       */
      public Builder clearAuth() {
        bitField0_ = (bitField0_ & ~0x00000001);
        auth_ = getDefaultInstance().getAuth();
        onChanged();
        return this;
      }
      /**
       * <code>required string auth = 1;</code>
       */
      public Builder setAuthBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        auth_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object needle_ = "";
      /**
       * <code>optional string needle = 2;</code>
       */
      public boolean hasNeedle() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional string needle = 2;</code>
       */
      public java.lang.String getNeedle() {
        java.lang.Object ref = needle_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            needle_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string needle = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNeedleBytes() {
        java.lang.Object ref = needle_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          needle_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string needle = 2;</code>
       */
      public Builder setNeedle(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        needle_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string needle = 2;</code>
       */
      public Builder clearNeedle() {
        bitField0_ = (bitField0_ & ~0x00000002);
        needle_ = getDefaultInstance().getNeedle();
        onChanged();
        return this;
      }
      /**
       * <code>optional string needle = 2;</code>
       */
      public Builder setNeedleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        needle_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.SuperSearchRequest)
    }

    // @@protoc_insertion_point(class_scope:proto.SuperSearchRequest)
    private static final com.ua.mytrinity.tv_client.proto.Search.SuperSearchRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ua.mytrinity.tv_client.proto.Search.SuperSearchRequest();
    }

    public static com.ua.mytrinity.tv_client.proto.Search.SuperSearchRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<SuperSearchRequest>
        PARSER = new com.google.protobuf.AbstractParser<SuperSearchRequest>() {
      @java.lang.Override
      public SuperSearchRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SuperSearchRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SuperSearchRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SuperSearchRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.ua.mytrinity.tv_client.proto.Search.SuperSearchRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SuperSearchResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.SuperSearchResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .proto.SuperSearchResponse.Result status = 1;</code>
     */
    boolean hasStatus();
    /**
     * <code>required .proto.SuperSearchResponse.Result status = 1;</code>
     */
    com.ua.mytrinity.tv_client.proto.Search.SuperSearchResponse.Result getStatus();

    /**
     * <code>repeated .proto.SearchResultRecord result = 2;</code>
     */
    java.util.List<com.ua.mytrinity.tv_client.proto.Search.SearchResultRecord> 
        getResultList();
    /**
     * <code>repeated .proto.SearchResultRecord result = 2;</code>
     */
    com.ua.mytrinity.tv_client.proto.Search.SearchResultRecord getResult(int index);
    /**
     * <code>repeated .proto.SearchResultRecord result = 2;</code>
     */
    int getResultCount();
    /**
     * <code>repeated .proto.SearchResultRecord result = 2;</code>
     */
    java.util.List<? extends com.ua.mytrinity.tv_client.proto.Search.SearchResultRecordOrBuilder> 
        getResultOrBuilderList();
    /**
     * <code>repeated .proto.SearchResultRecord result = 2;</code>
     */
    com.ua.mytrinity.tv_client.proto.Search.SearchResultRecordOrBuilder getResultOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code proto.SuperSearchResponse}
   */
  public  static final class SuperSearchResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.SuperSearchResponse)
      SuperSearchResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SuperSearchResponse.newBuilder() to construct.
    private SuperSearchResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SuperSearchResponse() {
      status_ = 0;
      result_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SuperSearchResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              com.ua.mytrinity.tv_client.proto.Search.SuperSearchResponse.Result value = com.ua.mytrinity.tv_client.proto.Search.SuperSearchResponse.Result.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                status_ = rawValue;
              }
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                result_ = new java.util.ArrayList<com.ua.mytrinity.tv_client.proto.Search.SearchResultRecord>();
                mutable_bitField0_ |= 0x00000002;
              }
              result_.add(
                  input.readMessage(com.ua.mytrinity.tv_client.proto.Search.SearchResultRecord.PARSER, extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) != 0)) {
          result_ = java.util.Collections.unmodifiableList(result_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ua.mytrinity.tv_client.proto.Search.internal_static_proto_SuperSearchResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ua.mytrinity.tv_client.proto.Search.internal_static_proto_SuperSearchResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ua.mytrinity.tv_client.proto.Search.SuperSearchResponse.class, com.ua.mytrinity.tv_client.proto.Search.SuperSearchResponse.Builder.class);
    }

    /**
     * Protobuf enum {@code proto.SuperSearchResponse.Result}
     */
    public enum Result
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>OK = 0;</code>
       */
      OK(0),
      /**
       * <code>NoAuth = 1;</code>
       */
      NoAuth(1),
      ;

      /**
       * <code>OK = 0;</code>
       */
      public static final int OK_VALUE = 0;
      /**
       * <code>NoAuth = 1;</code>
       */
      public static final int NoAuth_VALUE = 1;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Result valueOf(int value) {
        return forNumber(value);
      }

      public static Result forNumber(int value) {
        switch (value) {
          case 0: return OK;
          case 1: return NoAuth;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Result>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Result> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Result>() {
              public Result findValueByNumber(int number) {
                return Result.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.ua.mytrinity.tv_client.proto.Search.SuperSearchResponse.getDescriptor().getEnumTypes().get(0);
      }

      private static final Result[] VALUES = values();

      public static Result valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Result(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:proto.SuperSearchResponse.Result)
    }

    private int bitField0_;
    public static final int STATUS_FIELD_NUMBER = 1;
    private int status_;
    /**
     * <code>required .proto.SuperSearchResponse.Result status = 1;</code>
     */
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required .proto.SuperSearchResponse.Result status = 1;</code>
     */
    public com.ua.mytrinity.tv_client.proto.Search.SuperSearchResponse.Result getStatus() {
      @SuppressWarnings("deprecation")
      com.ua.mytrinity.tv_client.proto.Search.SuperSearchResponse.Result result = com.ua.mytrinity.tv_client.proto.Search.SuperSearchResponse.Result.valueOf(status_);
      return result == null ? com.ua.mytrinity.tv_client.proto.Search.SuperSearchResponse.Result.OK : result;
    }

    public static final int RESULT_FIELD_NUMBER = 2;
    private java.util.List<com.ua.mytrinity.tv_client.proto.Search.SearchResultRecord> result_;
    /**
     * <code>repeated .proto.SearchResultRecord result = 2;</code>
     */
    public java.util.List<com.ua.mytrinity.tv_client.proto.Search.SearchResultRecord> getResultList() {
      return result_;
    }
    /**
     * <code>repeated .proto.SearchResultRecord result = 2;</code>
     */
    public java.util.List<? extends com.ua.mytrinity.tv_client.proto.Search.SearchResultRecordOrBuilder> 
        getResultOrBuilderList() {
      return result_;
    }
    /**
     * <code>repeated .proto.SearchResultRecord result = 2;</code>
     */
    public int getResultCount() {
      return result_.size();
    }
    /**
     * <code>repeated .proto.SearchResultRecord result = 2;</code>
     */
    public com.ua.mytrinity.tv_client.proto.Search.SearchResultRecord getResult(int index) {
      return result_.get(index);
    }
    /**
     * <code>repeated .proto.SearchResultRecord result = 2;</code>
     */
    public com.ua.mytrinity.tv_client.proto.Search.SearchResultRecordOrBuilder getResultOrBuilder(
        int index) {
      return result_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasStatus()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeEnum(1, status_);
      }
      for (int i = 0; i < result_.size(); i++) {
        output.writeMessage(2, result_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, status_);
      }
      for (int i = 0; i < result_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, result_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ua.mytrinity.tv_client.proto.Search.SuperSearchResponse)) {
        return super.equals(obj);
      }
      com.ua.mytrinity.tv_client.proto.Search.SuperSearchResponse other = (com.ua.mytrinity.tv_client.proto.Search.SuperSearchResponse) obj;

      if (hasStatus() != other.hasStatus()) return false;
      if (hasStatus()) {
        if (status_ != other.status_) return false;
      }
      if (!getResultList()
          .equals(other.getResultList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasStatus()) {
        hash = (37 * hash) + STATUS_FIELD_NUMBER;
        hash = (53 * hash) + status_;
      }
      if (getResultCount() > 0) {
        hash = (37 * hash) + RESULT_FIELD_NUMBER;
        hash = (53 * hash) + getResultList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ua.mytrinity.tv_client.proto.Search.SuperSearchResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ua.mytrinity.tv_client.proto.Search.SuperSearchResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ua.mytrinity.tv_client.proto.Search.SuperSearchResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ua.mytrinity.tv_client.proto.Search.SuperSearchResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ua.mytrinity.tv_client.proto.Search.SuperSearchResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ua.mytrinity.tv_client.proto.Search.SuperSearchResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ua.mytrinity.tv_client.proto.Search.SuperSearchResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ua.mytrinity.tv_client.proto.Search.SuperSearchResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ua.mytrinity.tv_client.proto.Search.SuperSearchResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ua.mytrinity.tv_client.proto.Search.SuperSearchResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ua.mytrinity.tv_client.proto.Search.SuperSearchResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ua.mytrinity.tv_client.proto.Search.SuperSearchResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ua.mytrinity.tv_client.proto.Search.SuperSearchResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.SuperSearchResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.SuperSearchResponse)
        com.ua.mytrinity.tv_client.proto.Search.SuperSearchResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ua.mytrinity.tv_client.proto.Search.internal_static_proto_SuperSearchResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ua.mytrinity.tv_client.proto.Search.internal_static_proto_SuperSearchResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ua.mytrinity.tv_client.proto.Search.SuperSearchResponse.class, com.ua.mytrinity.tv_client.proto.Search.SuperSearchResponse.Builder.class);
      }

      // Construct using com.ua.mytrinity.tv_client.proto.Search.SuperSearchResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getResultFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        status_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (resultBuilder_ == null) {
          result_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          resultBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ua.mytrinity.tv_client.proto.Search.internal_static_proto_SuperSearchResponse_descriptor;
      }

      @java.lang.Override
      public com.ua.mytrinity.tv_client.proto.Search.SuperSearchResponse getDefaultInstanceForType() {
        return com.ua.mytrinity.tv_client.proto.Search.SuperSearchResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.ua.mytrinity.tv_client.proto.Search.SuperSearchResponse build() {
        com.ua.mytrinity.tv_client.proto.Search.SuperSearchResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.ua.mytrinity.tv_client.proto.Search.SuperSearchResponse buildPartial() {
        com.ua.mytrinity.tv_client.proto.Search.SuperSearchResponse result = new com.ua.mytrinity.tv_client.proto.Search.SuperSearchResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.status_ = status_;
        if (resultBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0)) {
            result_ = java.util.Collections.unmodifiableList(result_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.result_ = result_;
        } else {
          result.result_ = resultBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ua.mytrinity.tv_client.proto.Search.SuperSearchResponse) {
          return mergeFrom((com.ua.mytrinity.tv_client.proto.Search.SuperSearchResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ua.mytrinity.tv_client.proto.Search.SuperSearchResponse other) {
        if (other == com.ua.mytrinity.tv_client.proto.Search.SuperSearchResponse.getDefaultInstance()) return this;
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        if (resultBuilder_ == null) {
          if (!other.result_.isEmpty()) {
            if (result_.isEmpty()) {
              result_ = other.result_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureResultIsMutable();
              result_.addAll(other.result_);
            }
            onChanged();
          }
        } else {
          if (!other.result_.isEmpty()) {
            if (resultBuilder_.isEmpty()) {
              resultBuilder_.dispose();
              resultBuilder_ = null;
              result_ = other.result_;
              bitField0_ = (bitField0_ & ~0x00000002);
              resultBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getResultFieldBuilder() : null;
            } else {
              resultBuilder_.addAllMessages(other.result_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasStatus()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ua.mytrinity.tv_client.proto.Search.SuperSearchResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ua.mytrinity.tv_client.proto.Search.SuperSearchResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int status_ = 0;
      /**
       * <code>required .proto.SuperSearchResponse.Result status = 1;</code>
       */
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required .proto.SuperSearchResponse.Result status = 1;</code>
       */
      public com.ua.mytrinity.tv_client.proto.Search.SuperSearchResponse.Result getStatus() {
        @SuppressWarnings("deprecation")
        com.ua.mytrinity.tv_client.proto.Search.SuperSearchResponse.Result result = com.ua.mytrinity.tv_client.proto.Search.SuperSearchResponse.Result.valueOf(status_);
        return result == null ? com.ua.mytrinity.tv_client.proto.Search.SuperSearchResponse.Result.OK : result;
      }
      /**
       * <code>required .proto.SuperSearchResponse.Result status = 1;</code>
       */
      public Builder setStatus(com.ua.mytrinity.tv_client.proto.Search.SuperSearchResponse.Result value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        status_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .proto.SuperSearchResponse.Result status = 1;</code>
       */
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000001);
        status_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<com.ua.mytrinity.tv_client.proto.Search.SearchResultRecord> result_ =
        java.util.Collections.emptyList();
      private void ensureResultIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          result_ = new java.util.ArrayList<com.ua.mytrinity.tv_client.proto.Search.SearchResultRecord>(result_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.ua.mytrinity.tv_client.proto.Search.SearchResultRecord, com.ua.mytrinity.tv_client.proto.Search.SearchResultRecord.Builder, com.ua.mytrinity.tv_client.proto.Search.SearchResultRecordOrBuilder> resultBuilder_;

      /**
       * <code>repeated .proto.SearchResultRecord result = 2;</code>
       */
      public java.util.List<com.ua.mytrinity.tv_client.proto.Search.SearchResultRecord> getResultList() {
        if (resultBuilder_ == null) {
          return java.util.Collections.unmodifiableList(result_);
        } else {
          return resultBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .proto.SearchResultRecord result = 2;</code>
       */
      public int getResultCount() {
        if (resultBuilder_ == null) {
          return result_.size();
        } else {
          return resultBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .proto.SearchResultRecord result = 2;</code>
       */
      public com.ua.mytrinity.tv_client.proto.Search.SearchResultRecord getResult(int index) {
        if (resultBuilder_ == null) {
          return result_.get(index);
        } else {
          return resultBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .proto.SearchResultRecord result = 2;</code>
       */
      public Builder setResult(
          int index, com.ua.mytrinity.tv_client.proto.Search.SearchResultRecord value) {
        if (resultBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureResultIsMutable();
          result_.set(index, value);
          onChanged();
        } else {
          resultBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.SearchResultRecord result = 2;</code>
       */
      public Builder setResult(
          int index, com.ua.mytrinity.tv_client.proto.Search.SearchResultRecord.Builder builderForValue) {
        if (resultBuilder_ == null) {
          ensureResultIsMutable();
          result_.set(index, builderForValue.build());
          onChanged();
        } else {
          resultBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.SearchResultRecord result = 2;</code>
       */
      public Builder addResult(com.ua.mytrinity.tv_client.proto.Search.SearchResultRecord value) {
        if (resultBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureResultIsMutable();
          result_.add(value);
          onChanged();
        } else {
          resultBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.SearchResultRecord result = 2;</code>
       */
      public Builder addResult(
          int index, com.ua.mytrinity.tv_client.proto.Search.SearchResultRecord value) {
        if (resultBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureResultIsMutable();
          result_.add(index, value);
          onChanged();
        } else {
          resultBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.SearchResultRecord result = 2;</code>
       */
      public Builder addResult(
          com.ua.mytrinity.tv_client.proto.Search.SearchResultRecord.Builder builderForValue) {
        if (resultBuilder_ == null) {
          ensureResultIsMutable();
          result_.add(builderForValue.build());
          onChanged();
        } else {
          resultBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.SearchResultRecord result = 2;</code>
       */
      public Builder addResult(
          int index, com.ua.mytrinity.tv_client.proto.Search.SearchResultRecord.Builder builderForValue) {
        if (resultBuilder_ == null) {
          ensureResultIsMutable();
          result_.add(index, builderForValue.build());
          onChanged();
        } else {
          resultBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.SearchResultRecord result = 2;</code>
       */
      public Builder addAllResult(
          java.lang.Iterable<? extends com.ua.mytrinity.tv_client.proto.Search.SearchResultRecord> values) {
        if (resultBuilder_ == null) {
          ensureResultIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, result_);
          onChanged();
        } else {
          resultBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .proto.SearchResultRecord result = 2;</code>
       */
      public Builder clearResult() {
        if (resultBuilder_ == null) {
          result_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          resultBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .proto.SearchResultRecord result = 2;</code>
       */
      public Builder removeResult(int index) {
        if (resultBuilder_ == null) {
          ensureResultIsMutable();
          result_.remove(index);
          onChanged();
        } else {
          resultBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .proto.SearchResultRecord result = 2;</code>
       */
      public com.ua.mytrinity.tv_client.proto.Search.SearchResultRecord.Builder getResultBuilder(
          int index) {
        return getResultFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .proto.SearchResultRecord result = 2;</code>
       */
      public com.ua.mytrinity.tv_client.proto.Search.SearchResultRecordOrBuilder getResultOrBuilder(
          int index) {
        if (resultBuilder_ == null) {
          return result_.get(index);  } else {
          return resultBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .proto.SearchResultRecord result = 2;</code>
       */
      public java.util.List<? extends com.ua.mytrinity.tv_client.proto.Search.SearchResultRecordOrBuilder> 
           getResultOrBuilderList() {
        if (resultBuilder_ != null) {
          return resultBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(result_);
        }
      }
      /**
       * <code>repeated .proto.SearchResultRecord result = 2;</code>
       */
      public com.ua.mytrinity.tv_client.proto.Search.SearchResultRecord.Builder addResultBuilder() {
        return getResultFieldBuilder().addBuilder(
            com.ua.mytrinity.tv_client.proto.Search.SearchResultRecord.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.SearchResultRecord result = 2;</code>
       */
      public com.ua.mytrinity.tv_client.proto.Search.SearchResultRecord.Builder addResultBuilder(
          int index) {
        return getResultFieldBuilder().addBuilder(
            index, com.ua.mytrinity.tv_client.proto.Search.SearchResultRecord.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.SearchResultRecord result = 2;</code>
       */
      public java.util.List<com.ua.mytrinity.tv_client.proto.Search.SearchResultRecord.Builder> 
           getResultBuilderList() {
        return getResultFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.ua.mytrinity.tv_client.proto.Search.SearchResultRecord, com.ua.mytrinity.tv_client.proto.Search.SearchResultRecord.Builder, com.ua.mytrinity.tv_client.proto.Search.SearchResultRecordOrBuilder> 
          getResultFieldBuilder() {
        if (resultBuilder_ == null) {
          resultBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.ua.mytrinity.tv_client.proto.Search.SearchResultRecord, com.ua.mytrinity.tv_client.proto.Search.SearchResultRecord.Builder, com.ua.mytrinity.tv_client.proto.Search.SearchResultRecordOrBuilder>(
                  result_,
                  ((bitField0_ & 0x00000002) != 0),
                  getParentForChildren(),
                  isClean());
          result_ = null;
        }
        return resultBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.SuperSearchResponse)
    }

    // @@protoc_insertion_point(class_scope:proto.SuperSearchResponse)
    private static final com.ua.mytrinity.tv_client.proto.Search.SuperSearchResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ua.mytrinity.tv_client.proto.Search.SuperSearchResponse();
    }

    public static com.ua.mytrinity.tv_client.proto.Search.SuperSearchResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<SuperSearchResponse>
        PARSER = new com.google.protobuf.AbstractParser<SuperSearchResponse>() {
      @java.lang.Override
      public SuperSearchResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SuperSearchResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SuperSearchResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SuperSearchResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.ua.mytrinity.tv_client.proto.Search.SuperSearchResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_SearchResultRecord_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_SearchResultRecord_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_SuperSearchRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_SuperSearchRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_SuperSearchResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_SuperSearchResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014search.proto\022\005proto\"\230\001\n\022SearchResultRe" +
      "cord\0222\n\004type\030\001 \001(\0162$.proto.SearchResultR" +
      "ecord.RecordType\022\017\n\007id_list\030\002 \003(\005\"=\n\nRec" +
      "ordType\022\t\n\005Movie\020\000\022\013\n\007Channel\020\001\022\r\n\tEpgRe" +
      "cord\020\002\022\010\n\004News\020\003\"2\n\022SuperSearchRequest\022\014" +
      "\n\004auth\030\001 \002(\t\022\016\n\006needle\030\002 \001(\t\"\221\001\n\023SuperSe" +
      "archResponse\0221\n\006status\030\001 \002(\0162!.proto.Sup" +
      "erSearchResponse.Result\022)\n\006result\030\002 \003(\0132" +
      "\031.proto.SearchResultRecord\"\034\n\006Result\022\006\n\002" +
      "OK\020\000\022\n\n\006NoAuth\020\001B\"\n com.ua.mytrinity.tv_" +
      "client.proto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_proto_SearchResultRecord_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_SearchResultRecord_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_SearchResultRecord_descriptor,
        new java.lang.String[] { "Type", "IdList", });
    internal_static_proto_SuperSearchRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_SuperSearchRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_SuperSearchRequest_descriptor,
        new java.lang.String[] { "Auth", "Needle", });
    internal_static_proto_SuperSearchResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_proto_SuperSearchResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_SuperSearchResponse_descriptor,
        new java.lang.String[] { "Status", "Result", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
